- .gitignore
Not sure why that's not in .gitignore already, seems like it should be.
> ignores "VideoDecodeStats" in .gitignore

- README.md
- interface/resources/qml/hifi/dialogs/security/EntityScriptWhitelist.qml
- interface/src/Menu.cpp
- interface/src/Menu.h
- libraries/script-engine/src/ScriptEngine.cpp
The Entity Script Whitelist now combines the environment variables with the interface.json retrieved settings, there is now a QML interface under Settings (right below the Security... tab) to view and edit that interface.json whitelist.
Changes made to the whitelist through the QML interface will be reflected and be operational immediately. This allows for live handling of the whitelist without restarting interface. This opens up the door for creating temporary whitelists and accepting new domains for whitelists via prompt so users do not have to manually manage it.
> Whitelist added to interface.json, accessed by QML and C++

- libraries/render-utils/src/MeshPartPayload.cpp
With this change, it is no longer necessary to create the HIFI_ENABLE_MATERIAL_PROCEDURAL_SHADERS environment variable. Users only need to have the Developer menu active, and then check the menu option Developer->Render->Enable Procedural Materials
Tested on:
Windows 10 Pro 1909 build 18363.476
CMake 3.16.0
Microsoft Visual Studio Community 2019 Version 16.4.0
> Removes the environment variable requirement for procedural material shaders

- cmake/ports/sdl2/CONTROL
This fixes a build error when building the SDL2 library from vcpkg. Apparently, vcpkg on Linux doesn't like the `Homepage' entry.
> Update SDL2 CONTROL file to fix linux build

- plugins/openvr/src/OpenVrHelpers.cpp
fixes: [https://github.com/kasenvr/project-athena/issues/27](https://github.com/kasenvr/project-athena/issues/27)
Testing:
1. Close SteamVR.
2. Start Interface.
3. Wait until Interface fully loads.
Expected results:
SteamVR gets opened,
Interface doesn't take forever to load due to SteamVR
Audio still works.
> Audio Failure Due to missing VR fix

- libraries/render/src/render/CullTask.cpp
This fixes a possible crash with the secondary camera.
It's a hard one to repro cause it doesn't always happen.
But if you're turning the camera on and off a lot it can crash.
> Workaround for Secondary camera crash

- cmake/ports/etc2comp/portfile.cmake
- cmake/ports/hifi-scribe/portfile.cmake
- cmake/ports/nvtt/portfile.cmake
The highfidelity github repos will probably be going away on
Jan 15, 2020.
> Move to kasenvr repos

- libraries/ui/src/VrMenu.cpp
Otherwise eventually methods will be called on a NULL pointer.
Fixes crash related to QMetaObject::invokeMethod.
This patch produces the following warnings:
```
[12/26 00:19:09] [WARNING] [default] Failed to find addItem() method in object  QQmlComponent(0x1b9b0270) . Not inserting action  QAction(0x1d228520 text="Undo" toolTip="Undo" shortcut=QKeySequence("Ctrl+Z") menuRole=TextHeuristicRole visible=true)
[12/26 00:19:09] [WARNING] [default] Failed to find addItem() method in object  QQmlComponent(0x1b9b0270) . Not inserting action  QAction(0x7efbdc009580 text="Redo" toolTip="Redo" shortcut=QKeySequence("Ctrl+Y") menuRole=TextHeuristicRole visible=true)
[12/26 00:19:09] [WARNING] [default] Failed to find addItem() method in object  QQmlComponent(0x1b9b0270) . Not inserting action …
```
> Don't bind action if QML menu can't be added.

- interface/src/Application.cpp
Allows external whitelisting of QML files.
Requires the whole url (up to the .qml) in the entity script whitelist
e.g. 
sample urls:
https://realities.dev/cdn/qml/FloofChat.qml
http://home.darlingvr.club/hifi-community/FloofChat.qml
Test code:
```
var chatBar = new OverlayWindow({
source: "https://realities.dev/cdn/qml/FloofChat.qml",
width: 360,
height: 180
});
Script.setTimeout(function(){
chatBar.close();
},2000)
```
> QML Whitelisting

- interface/src/avatar/MyAvatar.cpp
The walk speed of your avatar is now proportional to your avatar's scale: small scales no longer run instead of walk; large scales no longer walk s l o w l y.
Tested:
- Desktop keyboard: walking (fixed), flying.
- Desktop gamepad: walking (fixed), flying.
- HMD walking, flying.
Desktop keyboard and gamepad walking were both broken; both are now fixed.
Issue: https://github.com/kasenvr/project-athena/issues/17
> Fix scaled avatar walk speed

- hifi_vcpkg.py
vcpkg throws an error when running cmake about a public key error. This resolves the possibility of the error showing up.
> Fix generating cmake

- interface/CMakeLists.txt
API documentation is put in \build\interface\Release\jsdoc directory when Interface is built.
> Re-enable JSDoc building

- interface/resources/qml/+webengine/QmlWebWindowView.qml
- interface/resources/qml/hifi/tablet/TabletRoot.qml
- interface/resources/qml/hifi/tablet/WindowRoot.qml
This PR stops Interface from throwing errors in the log because objects are sent over the EventBridge instead of strings.
Testplan:
Enable verbose mode by Developer>Scripting>Verbose Logging
Run the below code in script console with PR build,
If you see 
`[WARNING] [default] qrc:/qml/+webengine/QmlWebWindowView.qml:43: TypeError: Type error`
or
`[WARNING] [default] qrc:/qml/+webengine/QmlWebWindowView.qml:43: TypeError: Property 'slice' of object [object Object] is not a function`
then it did not work.
Code to run:
```
window = new OverlayWebWindow({ x: 5, y: 5, width: 640, height: 480 });
window.setURL("data:text/html;text,<html>[<script>setTimeout(function() { EventBridge.emitWebEvent({ type: 'buffer', data: [1,2,3,4,5,6] }) }, 1000);</script>]</html>//.html"); …
```
> Fixed clara rubbish

- interface/resources/qml/hifi/avatarPackager/AvatarPackagerApp.qml
- interface/resources/qml/hifi/avatarPackager/AvatarPackagerHeader.qml
- interface/resources/qml/hifi/avatarPackager/AvatarProject.qml
- interface/src/avatar/AvatarDoctor.cpp
- interface/src/avatar/AvatarProject.h
- Default project directory changed from C:/Users/USERNAME/Documents/High Fidelity Projects/ to C:/Users/USERNAME/Documents/Project Athena Projects/.
- Changed docs URL from https://docs.highfidelity.com/ to https://docs.projectathena.dev/.
- Removed (commented out) the "Video" button.
- Removed (commented out) the "Upload" button and associated items (e.g., "login required" message).
- Added "Open Project Folder" button.
- Reordered dialog content to make it flow better.
Issue: https://github.com/kasenvr/project-athena/issues/46
> Update Avatar Packager

- libraries/script-engine/src/WebSocketClass.cpp
- libraries/script-engine/src/WebSocketClass.h
Testplan:
Run the below code in script console with PR build,
result should look like ![this](https://fluffy.ws/u/zlSsea.png)
If it looks like ![this](https://fluffy.ws/u/sVGXPy.png)
then you don't have arraybuffer support!
Code to run:
```
var ws = new WebSocket('wss://echo.websocket.org');
ws.binaryType = 'arraybuffer';
ws.onmessage = function(evt) {
if (evt.data instanceof ArrayBuffer) {
console.info('received binary', evt.data.byteLength, 'bytes');
console.info('as floats', [].slice.call(new Float32Array(evt.data)));
} else {
console.info('received text', evt.data.length, 'chars', JSON.stringify(evt.data));
}       
};
ws.onopen= function() { 
console.info('connected', ws.url);
ws.send('._.');
ws.send(new Float32Array([0xFACE,Math.PI]).buffer)
ws.send('._.');
};
```
> Added ArrayBuffer support to websockets

- libraries/script-engine/src/ScriptEngine.cpp
This PR does the following: 
- Disables the whitelist on the server scripts.
- File:///, cache:, and atp: are hardcoded as defaults
- You can whitelist an entire domain e.g. "hifi://thepalace"
- A setting has been added to enable or disable the whitelist, however an interface toggle has not yet been added.
To test: 
- Build a server from Athena's master, try to run entity server scripts and check the log to see if the whitelist catches them. If there is no whitelist output, it should indicate they are getting through.
- Try to load a script from the file system and from the ATP, they should both get through without hassle.
- Try to whitelist a domain with many scripts that you have not whitelisted on it, they should be accepted.
- Modify the setting for "private/whitelistEnabled" and set …
> Whitelist Quality of Life Updates

- BUILD_LINUX.md
- hifi_utils.py
- hifi_vcpkg.py
This PR does several, related things:
* Makes it possible to use packages other than .tar.gz (for instance tar.xz and tar.bz2)
* Removes the usage of the deprecated platform.linux_distribution() functions.
* Adds experimental support for Ubuntu 19.10, by using a package I built and that is already uploaded to athena-public.
* Is a bit friendlier in the error reporting
> Add support for Ubuntu 19.10, modernize vcpkg

- scripts/communityModules/chat/FloofChat.html
- scripts/communityModules/chat/FloofChat.js
Testing is just,
on the chatbar on the bottom of the screen, you can do
/l to switch to local (default)
/d for domain
/g for grid
verify the above work.
/me is for firstperson talking so "/me sits" equates to "Fluffy sits"
"/goto thepalace" a window should popup asking if you want to go there (the same as when you click on a hifi:// url in the chat window)
if the placename/ip/url doesn't exist then it will silently fail as does all other gotos
Meow
> Added /l /d /g chatbar switches and /goto and /me

- libraries/networking/src/NetworkingConstants.h
- tools/nitpick/AppDataHighFidelity/Interface.json
We did have the dfault metaverse API as metaverse.projectathena.io, but that doesn't not yet exist, and it turns out we can't just do a redirect. So for now changing it to metaverse.highfidelity.com
> Quick fix for the metaverse API

- libraries/gpu-gl-common/src/gpu/gl/GLBackendState.cpp
- libraries/gpu-gl-common/src/gpu/gl/GLState.cpp
- libraries/gpu/src/gpu/Format.h
- libraries/gpu/src/gpu/State.cpp
- libraries/gpu/src/gpu/State.h
When building with GCC, it generates 3020 warnings like this:
libraries/gpu/src/gpu/State.h:208:18: warning: ‘gpu::State::BlendFunction::destColor’
is too small to hold all values of ‘enum gpu::State::BlendArg’
This is because ‘enum gpu::State::BlendArg’ is declared as an enum
of uint16 size, and gpu::State::BlendFunction::destColor is a bit
field.
GCC correctly deduces that a 16 bit value won't always fit in a 4
bit field, and emits a warning.
The problem is that the amount is such that it floods the output and hides
other warnings.
Changing the 'enum foo : uint16' declarations to 'enum foo' stops gcc
from emitting the warning.
Making this change required the removal of a set of assertion checks. At least
empirically they seem unnecessary -- the interface compiles and runs fine.
> Fix thousands of 'is too small to hold all values' warnings on Linux

- tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
Fixes the initial value not counting because it was setting as a string instead of a bool.
> APIDocs theme toggle bugfix

- tools/jsdoc/hifi-jsdoc-template/static/styles/night.css
Nightmode: Code no longer has a BG unless it is in a block, all other main non-block code tags are bolded for visibility. Comments in codeblocks are now a bit brighter.
> Update API Docs for readability

- scripts/defaultScripts.js
To enable run 
`Settings.setValue("_betaDefaultScriptsIsChecked", true);`
in your script console and then restart your default scripts or restart interface
(You may have to stop the FloofChat.js script first before it will switch to the beta version)
> Added basic beta default scripts feature

- interface/src/raypick/StylusPick.h
- libraries/animation/src/AnimInverseKinematics.h
- libraries/entities/src/EntityItemProperties.h
- libraries/entities/src/SimulationOwner.h
- libraries/image/src/image/Image.h
- libraries/shared/src/CubicHermiteSpline.h
- libraries/shared/src/shared/MediaTypeLibrary.h
Recent versions of gcc generate a warning without this. This follows the deprecation of this in the C++11 standard. The result is a huge amount of warnings in the Linux build.
This change should be pretty much a no-op, because everything was declared as "= default", meaning the compiler will keep doing exactly what it was doing before just without a warning.
The reasoning for this change is the rule of three: https://en.cppreference.com/w/cpp/language/rule_of_three
> If a class requires a user-defined destructor, a user-defined copy constructor, or a user-defined copy assignment operator, it almost certainly requires all three.
So, I reviewed those classes, and so far my conclusion that a default copy constructions and operator= should work correctly, but I definitely would welcome second …
> Make default copy constructors explicit

- interface/src/Application.cpp
- interface/src/Application.h
- interface/src/main.cpp
- libraries/networking/src/AddressManager.cpp
- libraries/networking/src/DomainHandler.cpp
- libraries/octree/src/Octree.cpp
- libraries/octree/src/Octree.h
- Add support for serverless domains via HTTP/HTTPS.
- Fix missing "no connection" dialog for invalid serverless domains.
- Add support for serverless domains via FILE and HTTP/HTTPS in the --url command line parameter.
Issue: https://github.com/kasenvr/project-athena/issues/106
> Add support for serverless domains via HTTP/HTTPS

- interface/resources/qml/hifi/audio/Audio.qml
- interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
- interface/resources/qml/windows/ScrollingWindow.qml
A vertical scrollbar is always displayed for the following Settings dialogs:
- Settings > General
- Settings > Audio > Desktop
- Settings > Controls > Settings
The scrollbars are displayed in both in window and in tablet modes, desktop and HMD.
This provides a visual prompt to the user that there is more dialog content above/below.
Issue: https://github.com/kasenvr/project-athena/issues/98
> Always display vertical scrollbar in Settings dialogs that scroll

- cmake/init.cmake
- interface/CMakeLists.txt
Fixes crashes on shutdown on Linux, see  #151 
Static libraries result in misbehavior on Linux. Here's my understanding of what happens:
1. You do a `static Foo foo;` in shared.
2. Logically, this creates a call to the `Foo` constructor.
3. Shared gets statically linked into both libfoo and libbar. Of course each of those now has the constructor call. They're static, so each has to include that code.
4. Both libfoo and libbar get statically linked into libplugin, which now gets two copies of the same code, and stuff gets  called twice.
This results in crashes on shutdown as destructors get called more than once, and this results in a double-free. This is sort of harmless, but there are possible grave issues:
1. Constructors also are called multiple times. This will overwrite the global …
> Force dynamic build on Linux

- libraries/script-engine/src/ScriptEngines.cpp
Issue: https://github.com/kasenvr/project-athena/issues/122
> Fix scripts not running at Interface start after reloading all scripts

- scripts/defaultScripts.js
- scripts/simplifiedUI/ui/simplifiedNametag/simplifiedNametag.js
Also made it so that it disables while using the inspect.js script.
Test plan:
When using the inspect.js script (holding the alt key), click on an avatar multiple times as you zoom in, out, and around that person. Ensure the nametag does not show up. Now stop using the inspect script, click on them again and observe that the nametags do show, timeout, or disappear when clicked again.
> Makes simplified nametag a default script

- libraries/networking/src/AddressManager.cpp
Issue: https://github.com/kasenvr/project-athena/issues/147
> Fix server logs filling up with "/"s

- scripts/defaultScripts.js
To test: 
- Check the box under Developer > Scripting. 
- You will want to reload your default scripts, or restart the interface if you want to be extra sure. The floofchat app should now be loading from the URL instead of the folder. 
- Uncheck, reload the default scripts or restart the interface. The floofchat app should now be loading from the folder as before.
> Adds menu toggle for beta default scripts

- BUILD.md
- BUILD_ANDROID.md
- BUILD_LINUX.md
- BUILD_OSX.md
- BUILD_WIN.md
TODO: We need absolute paths because when they are pulled into the docs, the links are of course broken as there is no actual repo there.
> Update build docs.

- libraries/gpu/src/gpu/FrameReader.cpp
Building in the latest version of Visual studio 2019 fails with a `'operator =' is ambigious` error. This small patch will fix the error.
> Fix VS2019 (Version 16.5.1) builds

- interface/src/Menu.cpp
- interface/src/Menu.h
- interface/src/main.cpp
- interface/src/ui/PreferencesDialog.cpp
- libraries/networking/src/UserActivityLogger.cpp
- libraries/networking/src/UserActivityLogger.h
separate user activity logging from crash logging, allowing people to say "no" to tracking while still sending crashes
Adds new setting CrashLoggerDisabled along with a new corresponding user preference.
> Separate user activity logging from crash logging

- interface/src/scripting/WindowScriptingInterface.h
- interface/src/ui/Snapshot.cpp
This should change the name when taking a snapshot (screenshot) to vircadia-snap-by-... rather than hifi-snap-by-...
I just ran `grep -r hifi-snap-by *` to find all related mentions in the source code.
> Change standard snapshot name to vircadia

- interface/src/Application.cpp
- interface/src/CrashHandler_Crashpad.cpp
Currently the information that is sent when Interface crashes is not tuned to Sentry; because of this most of the information is simply included at the bottom of the dump.  This tweaks the names of the attributes to give hints on how Sentry should interpret them.
> Improve information sent to Sentry on crashes

- libraries/entities/src/EntityTree.cpp
Currently interface crashes very quickly on master when built with debug enabled, see #337 
This patch attempts to fix that, and it seems to work, but issues almost instantly crop up elsewhere, somewhere from the scripting engine apparently. So this fix could well be completely incorrect.
Submitting this for feedback.
> Attempt to fix #337 by ensuring the object is marked as dead.

- libraries/entities-renderer/src/paintStroke.slf
- libraries/graphics/src/graphics/Material.slh
- libraries/render-utils/src/CullFace.slh
- libraries/render-utils/src/model.slf
- libraries/render-utils/src/simple.slf
- libraries/render-utils/src/simple_procedural.slf
https://github.com/kasenvr/project-athena/issues/297
To test, both of these models should appear correctly lit/shadowed:
https://aitolda.s3.amazonaws.com/FreeAgentSource/Island/Palm1Static.fbx
https://aitolda.s3.amazonaws.com/FreeAgentSource/Island/Palm1Static.glb
> Models support flipped normals on double sided geometry

- scripts/system/create/edit.js
Changed the code so that no entities are grabbable by default anymore.
As I cannot see why anyone would want this unless this option was easily toggleable, I completely removed that part of the code.
Tested if it works and doesn't break anything that might be related to it.
Closes #209
> Disable "grabbable" property by default

- launchers/qt/src/BuildsRequest.h
- launchers/qt/src/LauncherState.cpp
- launchers/qt/src/LauncherState.h
- launchers/qt/src/UserSettingsRequest.h
- libraries/shared/src/PathUtils.h
- tools/oven/src/BakerCLI.h
- tools/oven/src/OvenCLIApplication.cpp
It's deprecated and produces a warning on Qt 5.14. It produces lots of:
'QString::null' is deprecated: use QString() [-Wdeprecated-declarations]
when compiling.
> Remove all uses of QString::null

- interface/src/Application.cpp
This cannot be tested until there is a QML based app in the community-apps repo, we should get the Spectator cam merged first in order to test this.
Closes #295
> Add community-apps repo to default QML whitelist.

- interface/src/avatar/MyAvatar.cpp
- libraries/entities/src/EntityTree.cpp
- libraries/entities/src/EntityTree.h
- libraries/shared/src/SpatiallyNestable.cpp
- libraries/shared/src/SpatiallyNestable.h
Run [this script](https://gist.githubusercontent.com/HifiExperiments/8f79e199b1f132f06e512a18f91c3b53/raw/3ea3bfcee0fdd5849eba8f53394eafd510f6724f/ModelParenting.js).  You'll see a bunch of mannequins in front of you.  Press 'o'.  This will make the bottom model a child of your avatar.  On master, your framerate will basically go to 0.  Now, your framerate will still drop, but not nearly as much, and interface should still be usable.
> Improve performance of MyAvatar::simulate when you have lots of descendants

- interface/src/avatar/MyAvatar.cpp
- interface/src/avatar/MyAvatar.h
Flying in VR is now enabled by default in new Interface installations (and if Interface.json settings are deleted): Settings > Controls > Settings > VR Movement > Jumping and flying option is enabled by default.
> Enable flying in VR by default

- libraries/ktx/src/khronos/KHR.h
- libraries/shared/src/shared/Storage.h
Found that building project-athena on Windows10 with Visual Studio 2019 using the latest CMake integrated in VS required the inclusion of these 'include' files. These 'includes' do not seem to be needed on Linux so I presume the problem is that the include dependency tree is a little different on Windows10.
> Include <stdexcept> for building on Windows10 with Visual Studio 2019

- interface/src/Menu.cpp
- interface/src/Menu.h
- libraries/networking/src/UserActivityLogger.h
The crash logger could end up sending some private data, so just in case it's now off by default.
This change won't affect existing installations, only the default is modified.
> Disable crash logger by default

- libraries/audio-client/src/AudioClient.cpp
This fixes the constant stream of:
[06/07 15:18:15] [DEBUG] [hifi.audioclient] getAvailableDevices Default device not found in list: "" Setting Default to:  "pulse"
[06/07 15:18:17] [DEBUG] [hifi.audioclient] getAvailableDevices Default device not found in list: "" Setting Default to:  "pulse"
[06/07 15:18:18] [DEBUG] [hifi.audioclient] getAvailableDevices Default device not found in list: "" Setting Default to:  "pulse"
[06/07 15:18:20] [DEBUG] [hifi.audioclient] getAvailableDevices Default device not found in list: "" Setting Default to:  "pulse"
[06/07 15:18:20] [DEBUG] [hifi.audioclient] getAvailableDevices Default device not found in list: "" Setting Default to:  "pulse"
Linux had no default audio implementation, implemented using QAudioDeviceInfo.
Speaking of which, is there some …
> Fix Linux default audio device debug messages

- libraries/entities/src/EntityTree.cpp
I've neutered the auto-deletion for entities that are certified, however I kept intact the verification checks.
What should be done next: move certified checks into their own files. Certified checks will get routed through the metaverse API that you are connected to, it is up to that API if it cares or not. The next thing to do after that is to allow you to change the certified URL by setting so you can have a certifying authority that is not routed through your metaverse API provider.
**To test:**
Launch your sandbox and try to rez a certified entity that does not allow copies multiple times. To verify that it is working, you can read in your server-console's assignment client logs where the check is happening, it will have a line along the lines of "No action will be taken to delete the …
> Disable Certified Entity Auto Deletion

- libraries/networking/src/DomainHandler.cpp
- Reloading content in serverless domain (e.g., file:///~/serverless/tutorial.json) should now work. 
- Reloading content in normal domain should still work.
> Fix reloading content in serverless domain

- scripts/system/create/edit.js
**Issue:** Loading a model through the Create App would cause its dimensions to be set to 1m^3. This would happen because the app would wait for the model to load before checking its dimensions and setting them, however the app had a strict timeout of 1s. So, if the model is in your cache then it would work. If the model was cachebusted or just in general new, it would not work as the loading would *likely* take more than 1 second.
**Solution:** I raised the timeout to 10 seconds and also put a message if the model gets wrongly sized due to running out of time that way the user will at least have some indication of what happened, and why, and so will developers.
**Test Plan:** Load a model entity into the world that is not cached, cachebust one if you would like. If it comes in under 10 …
> Fix models not scaling correctly when loading due to timeout.

- scripts/defaultScripts.js
To solve the problem of on startup the script tried to load and cannot so a QML dialog box appears to that effect.
> Remove script that no longer exists created by the Vive Pro Eye PR.

- interface/src/Application.cpp
- interface/src/Application.h
- interface/src/Menu.cpp
- libraries/networking/src/AddressManager.h
This so that the serverless tutorial can be readily revisited.
Also fixed up JSDoc for AddressManager.handleLookupString().
> Add Help > Tutorial menu item

- libraries/shared/src/NumericalConstants.h
A report was made in #mac of this crash:
```
Thread 2 received signal SIGILL, Illegal instruction.
0x00000001105fc4e4 in __cxx_global_var_init () from /Users/davek/builds/project-athena/build/libraries/audio/Debug/libaudio.dylib
(gdb) bt
#0  0x00000001105fc4e4 in __cxx_global_var_init ()
from /Users/davek/builds/project-athena/build/libraries/audio/Debug/libaudio.dylib
#1  0x00000001105fc529 in _GLOBAL__sub_I_AudioHRTF_avx512.cpp ()
from /Users/davek/builds/project-athena/build/libraries/audio/Debug/libaudio.dylib
#2  0x0000000103897592 in ?? ()
#3  0x000000011e24f000 in ?? ()
#4  0x000000011f070000 in ?? () from /Users/davek/builds/project-athena/build/libraries/gl/Debug/libgl.dylib
#5  0x000000011056d000 in ?? ()
warning: (Internal error: pc 0x0 in read in psymtab, but not in symtab.) …
```
> Fix illegal instruction in libaudio.dylib on OSX

- interface/src/Application.cpp
- interface/src/Application.h
- interface/src/scripting/ClipboardScriptingInterface.cpp
- interface/src/scripting/ClipboardScriptingInterface.h
- libraries/entities/src/EntityTree.cpp
- libraries/entities/src/EntityTree.h
It defaults to "domain" if not specified.
Closes #488 
Test plan, make sure that:
- you can still call the method without specifying host type
- it works for all three host types and that the functionality works as expected for all three host types.
> Add ability to paste entities to any host type

- interface/resources/qml/hifi/audio/Audio.qml
This PR moves the volume control up, so you don't have to scroll all the way to the bottom just to change your volume.
The "Test your voice" and "Test your sound" buttons have been moved to the top of their categories, so, again, you don't have to scroll down as much to test your stuff. This makes sense, since you might want to test your audio, before changing it. The most helpful audio device options also appear at the top of their list (at least on linux).
I also shortened the PushToTalk info text for VR, since that was longer than the window would show.
I tested this PR on Linux Mint 19.3
> Little "Audio" settings UI improvements

- interface/src/ModelPackager.cpp
- libraries/hfm/src/hfm/HFM.h
- libraries/image/src/image/TextureProcessing.cpp
There is interest in increasing the maximum texture size. This seems reasonable, since most of our users own their own domain, and decide which kinds of users to target, so there seems little need to restrict them.
According to https://feedback.wildfiregames.com/report/opengl/feature/GL_MAX_TEXTURE_SIZE the 8192 size should be supported by 90% of the surveyed hardware, which includes 10 year old cards. That seems quite reasonable.
This needs testing to see if:
1. A 8192x8192 texture actually works
2. What happens when it's used on hardware that doesn't support it (if we can find hardware old enough)
> Increase maximum texture size to 8192

- interface/CMakeLists.txt
- launchers/darwin/CMakeLists.txt
- launchers/qt/CMakeLists.txt
- launchers/qt/resources/qml/HFControls/HFTextLogo.qml
- launchers/qt/src/Launcher.cpp
- launchers/qt/src/LauncherInstaller_windows.cpp
- launchers/qt/src/main.cpp
- launchers/win32/LauncherManager.cpp
- screenshare/packager.js
- tools/nitpick/src/TestRunnerDesktop.cpp
This PR changes some strings, folders and comments from "High Fidelity" to "Vircadia".
While most of the rebranded components seem unused to me, this PR should fix the Interface showing up as "High Fidelity" on macOS.
I will try building and running this on macOS.
EDIT: my macOS broke so I will not try building and running on macOS..
> Change strings, comments and folders to Vircadia rebrand

- assignment-client/src/Agent.cpp
Repro the issue - https://github.com/kasenvr/project-athena/issues/518 - with current Vircadia release then test that this PR fixes the issue.
Use both the Interface and the Sandbox from this PR while testing.
You can use the playRecordingAC.js AC script from the URL mentioned in the dialog, i.e.: https://cdn.vircadia.com/community-apps/applications/record/playRecordingAC.js
Test with a single AC script instance:
- Test one recording - loading, unloading, and loading it again. The avatar should be displayed both times.
- Test two separate recordings that have different avatars - loading one, unloading it, loading the other. The correct avatar should be displayed each time.
> Fix avatar not displaying when recording is re-loaded

- libraries/fbx/src/FBXSerializer_Mesh.cpp
Fixes issue: https://github.com/kasenvr/project-athena/issues/294
> Fix display of FBX models with only one color for vertices

- interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
Settings > Graphics dialog, "Resolution Scale" slider now goes up to 2.0 (instead of 1.0).
Notes:
- This slider is adjustable if the graphics setting is set to "Custom".
- Custom graphics settings are not save between program runs. https://github.com/kasenvr/project-athena/issues/35
> Increase graphics settings' resolution scale item maximum to 2.0

- domain-server/src/DomainGatekeeper.cpp
- domain-server/src/DomainGatekeeper.h
- libraries/networking/src/DomainHandler.cpp
- libraries/networking/src/DomainHandler.h
- libraries/networking/src/NodeList.cpp
- libraries/networking/src/NodePermissions.h
- Distinguishes not logged into metaverse from not logged into domain.
- Applies permissions for groups (user roles) from domain login.
- Generates "not authorized on domain" condition (with stubs for related OAuth2 code).
> Domain login groups and "not authorized on domain"

- scripts/system/snapshot.js
This should fix occurrences of the Snapshot app dialog appearing in snapshots, which can occasionally happen at present.
This is hard to test because the problem is hard to reproduce. It can be artificially reproduced by setting, say, the `ECO_PROFILE` game rate targets to 1Hz in RefreshRateManager.cpp and removing the timeout for `Window.takeSnapShot()` in snapshot.js.
> Delay taking snapshot further at low render rates

- interface/src/Application.cpp
Fixes the `--url` command line option to work both with a `=` and with a ` ` as the separator between the `--url` and the domain value.
Doesn't fix other command line options that have similar problems. (See https://github.com/kasenvr/project-athena/issues/446) These will be fixed in a subsequent PR.
> Fix --url command line parameter to work with both "=" and " "

- domain-server/resources/web/assignment/placeholder.js
When you click on the Assignment tab in the server settings, the placeholder comments refer to hifi github, so changing it to vircadia github. :)
> changed url for AC script examples from HiFi to Vircadia github

- libraries/octree/src/Octree.cpp
- libraries/octree/src/Octree.h
- libraries/octree/src/OctreeEntitiesFileParser.cpp
- libraries/octree/src/OctreeEntitiesFileParser.h
This is useful when writing your own entities json and you have exported models or assets nearby. For example, exporting blender/unity scenes so it can be imported easily or writing procedural scenes not knowing where the content is hosted.
I've already tested this locally and every property gets correctly resolved.
> Allow resolving relative urls when importing entities json

- interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
- interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
- interface/src/AboutUtil.h
- interface/src/Application.cpp
- scripts/system/interstitialPage.js
This duplicates the `HifiAbout` API and adds an `About.platform` property that returns `"Vircadia"`.
The old `HiFAbout` API is still provided but it is labelled as "deprecated" in the API docs.
> Add "About" JavaScript API and platform string

- interface/src/Application.cpp
- interface/src/Menu.cpp
- libraries/networking/src/DomainAccountManager.cpp
- libraries/networking/src/DomainAccountManager.h
- libraries/networking/src/DomainHandler.cpp
- libraries/networking/src/NodeList.cpp
The following items are only displayed on domains that have domain login:
- Title bar: (Domain: <login status>)
- Menu item: The File > Domain: Log In 
Also:
- Ignores "connection denied" packets from previous domain, to prevent erroneous domain login dialog displaying.
- Handles domain login for multiple WordPress domains. (Can log into one, teleport to another and log in there also, then teleport between the two without having to log in again.)
> Don't display domain log-in items unless relevant

- interface/src/ModelPackager.cpp
- libraries/avatars-renderer/src/avatars-renderer/Head.cpp
- libraries/fbx/src/FBXSerializer.cpp
- libraries/fbx/src/FST.cpp
- libraries/fbx/src/GLTFSerializer.cpp
- libraries/fbx/src/GLTFSerializer.h
- libraries/hfm/src/hfm/HFM.cpp
- libraries/hfm/src/hfm/HFM.h
- libraries/shared/src/BlendshapeConstants.cpp
- libraries/shared/src/BlendshapeConstants.h
This PR fixes up and extends the support for blendshapes on glTF models - both for entities and avatars, and both with and without using FST files.
Changes include:
- Fix application of glTF blendshapes (on model with one mesh).
- Fix (removes) erroneous weighting of glTF blendshapes by default blendshape values.
- Add support for glTF blendshapes on meshes comprising more than one submesh (glTF primitive).
- Add support for glTF blendshapes on models with more than one mesh.
- Add support for blendshapes in glTF models used directly without an FST. (The model must use standard blendshape names.)
- Blendshapes configured in an FST override blendshapes in the glTF model. (But any in the model that aren't overridden are still used.)
- Add HFM model debug dump for FBX models.
Note: Both …
> Fix and extend glTF blendshapes support

- libraries/fbx/src/GLTFSerializer.cpp
This PR fixes the problem of pick rays not intersecting many glTF entities.
> Fix pick rays not intersecting glTF models

- interface/resources/qml/Browser.qml
Adds a button to the right of the URL box that opens the URL in an external browser, and closes the Interface browser window. This button is only enabled in desktop mode.
Also:
- Fixes colors of prev, next, and stop/reload buttons so that they're visible.
- Fixes action of stop/reload button.
- Fixes display of Web page's favicon.
- Adds hover action to prev, next, and stop/reload buttons.
- Fixes (works around bug in) location history: when you manually type in a new URL the location history is updated (and prev/next buttons work) rather than it only working when clicking on links in the Web page.
> Add open-in-external-browser button to web browser dialog

- libraries/ui/src/ui/types/ContextAwareProfile.cpp
- libraries/ui/src/ui/types/ContextAwareProfile.h
This concerns a class responsible for checking if webpages are restricted from making outside requests.  The previous implementation would do a (cross-thread blocking) retrieval of a QML property (with a one-second cache).  Unfortunately I have been seeing (from debugger, so not necessarily a real-world situation) a consistent deadlock where the value was being retrieved during app shutdown.
The new approach sets up a signal+slot attempting to forward any changes to RestrictFileAccess at the time they occur, the only time the QML value is retrieved is at the point of class construction.  Retrieving the value is done from a QAtomicInt with no blocking.
The only change in behavior should be that RestrictFileAccess is no longer (consistently) changeable from QML script.  Is this something …
> [shutdown-deadlock] Restructure ContextAwareProfile from polling to notifications

- libraries/audio-client/src/AudioClient.cpp
Fix double locking attempt if waitForFinished causes prepareLocalAudioInjectors to be called on this thread.
Co-Authored-By: Heather Anderson <1115056+odysseus654@users.noreply.github.com>
> Fix audio output switching crash

- interface/src/Application.cpp
If you're on a serverless domain, the Interface title bar currently starts with "serverless:". This PR fixes this so that it reads "Serverless:".
> Fix "Serverless" capitalization in title bar

- assignment-client/src/AssignmentClientApp.cpp
During my review of wallet+marketplace dependencies I found what appears to be a copy/paste bug in assignment-client parameter handling effectively preventing the -a and -p options from being used if the -wallet option was absent (and then assuming both were present if -wallet was present)
This is being committed without testing other than basic compilation testing as part of the wallet PR
> apparent copy/paste bug on assignment-client parameters

- plugins/hifiSdl2/CMakeLists.txt
GCC 10 and above sets -fno-common by default, and causes a linking problem here:
Multiple definition of `WAYLAND_wl_proxy_marshal'
Work around it per https://medium.com/@clentfort/using-esy-sdl2-with-gcc-10-91b4fa0c5aa9
This fixes the build on Fedora 32, and similarly new distributions that come with GCC 10.
This is probably not the best fix possible, since the better thing to do would be to fix the linking issue, but I've not dug into the details of why it happens, and why only with the Wayland symbols.
> Fix build of hifiSdl2 on GCC 10

- libraries/entities/src/EntityItemProperties.cpp
- libraries/octree/src/OctreeEntitiesFileParser.cpp
Relative URLs can now be used in the `textures` property for Model entities in JSONs.
> Support relative JSON URLs in model textures property

- pkg-scripts/docker-vircadia-supervisor.conf
Add --get-temp-name to domain-server invocation in creation of Docker domain-server image in pkg-scripts. This parameter is required by the domain-server so it will fetch a temporary domain name if it is not configured.
> Add --get-temp-name to domain-server invocation in creation of Docker

- libraries/networking/src/ExternalResource.cpp
- libraries/networking/src/ExternalResource.h
- libraries/script-engine/src/ScriptEngine.h
* Remove leading slashes, so that the path included in the bucket's path can't be overriden
* Remove any duplicated slashes always
* Small warning fix -- multiline comment
> Sanitize URLs in ExternalResources

- domain-server/src/DomainGatekeeper.cpp
- interface/src/avatar/OtherAvatar.cpp
- interface/src/ui/OctreeStatsDialog.cpp
- libraries/entities-renderer/src/RenderableEntityItem.h
- libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
- libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
- libraries/gpu-gl-common/src/gpu/gl/GLBackendState.cpp
- libraries/gpu-gl-common/src/gpu/gl/GLBackendTransform.cpp
- libraries/graphics-scripting/src/graphics-scripting/ScriptableMeshPart.cpp
- libraries/image/src/image/CubeMap.cpp
- libraries/octree/src/OctreePacketData.cpp
- libraries/render-utils/src/RenderPipelines.cpp
- libraries/shared/src/BufferParser.h
- libraries/shared/src/GeometryUtil.cpp
- libraries/shared/src/avx2/BlendshapePacking_avx2.cpp
- libraries/shared/src/shared/ConicalViewFrustum.cpp
- plugins/KasenAPIExample/src/KasenAPIExample.cpp
This fixes a whole bunch of build-time warnings emitted by GCC on Linux
* An incorrect fall-through (so an actual bug)
* Suppress fall-through warnings where a fall-through was intended
* Fix an "X will be initialized after Y" warning (possible bug resulting in a variable not being correctly initialized)
* Fix numerical precision warning
* Fix warnings about signed and unsigned comparison
* Fix a set of Wclass-memaccess warnings.
The last one needs a good looking at, because it touches rendering code. Some of this kind still remain, to be addressed later. I fixed the ones relating to glm:: data types, since GLM is an external library we can't modify. The rest belong to Vircadia code which can be changed.
> Fix warnings emitted by GCC

- assignment-client/src/audio/AudioMixerClientData.h
- assignment-client/src/audio/AudioMixerSlave.h
- libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
- libraries/material-networking/src/material-networking/TextureCache.cpp
- libraries/shared/src/RegisteredMetaTypes.h
- libraries/shared/src/TBBHelpers.h
This fixes the build on Qt 5.14 and above. Tested on 5.14.2 and 5.15.
Building under new Qt versions generates a lot of deprecation warnings, those will be addressed later.
So far 5.14.2 seems to work fine, and 5.15 seems to hang shortly after start for an unknown reason. The end goal here is to get 5.15 to work, since that should be the first version Vircadia can use without patching.
> Fix build on qt 5.14

- libraries/entities-renderer/src/RenderableGizmoEntityItem.h
- libraries/fbx/src/GLTFSerializer.cpp
Fix more warnings in the Linux build process.
This one is quite trivial -- it adds a missing override, and removes an unused variable. There's still a few more to go, but the build is almost clean now!
> Fix more warnings

- .eslintrc.js
- interface/src/AboutUtil.cpp
- interface/src/AboutUtil.h
- interface/src/scripting/WindowScriptingInterface.cpp
- interface/src/scripting/WindowScriptingInterface.h
- scripts/communityScripts/chat/FloofChat.js
Chat hypelinks are opened in an Interface browser window rather than a custom window (without address bar etc. controls).
Also:
- Adds an optional URL parameter to `Windows.openWebBrowser()`.
- Fixes an Interface crash in `About.openUrl()`.
- Adds the `About` API to ESLint list of known globals.
- Minor update to `About.openUrl()` JSDoc.
@FluffyJenkins
> Open chat hyperlinks in Interface browser window

- interface/CMakeLists.txt
- libraries/display-plugins/CMakeLists.txt
- libraries/gl/CMakeLists.txt
- libraries/gpu-gl-common/CMakeLists.txt
- libraries/gpu-gl/CMakeLists.txt
- libraries/qml/CMakeLists.txt
- libraries/ui/CMakeLists.txt
- tools/gpu-frame-player/CMakeLists.txt
This should be a no-op, besides generating less build warnings,
since:
"CMake 3.11 and above prefer to choose GLVND libraries."
And 3.11 is a few years old at this point, so this is almost certainly what everyone is building with anyway.
This fixes a bunch of these:
```
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenGL.cmake:305 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so
OpenGL_GL_PREFERENCE has not …
```
> Set GL preference to GLVND

- interface/resources/controllers/keyboardMouse.json
- interface/src/Application.cpp
- interface/src/Application.h
- interface/src/FancyCamera.h
- interface/src/ui/PreferencesDialog.cpp
- libraries/display-plugins/src/display-plugins/CompositorHelper.cpp
- libraries/display-plugins/src/display-plugins/CompositorHelper.h
- libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
- libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.h
- libraries/shared/src/shared/Camera.h
(Currently not hooked up to any scripts or keys)
To enable, in console: `Camera.captureMouse = true;`
Set to false to disable.
Needs to be tested on other OSes, and not sure how it interacts with the mouse logic in HMD
> Add option to capture mouse

- libraries/fbx/src/GLTFSerializer.cpp
If a glTF (.glTF or .glb) model has a blendshape with a target mesh missing, this can can result in crosslinking of blendshapes (the blendshape value affects an unintended mesh) or an Interface crash when the model is loaded.
Repro: Using current release or master, rez the following model: http://ctrlaltstudio.com/downloads/vircadia-dev/gltf/hapticMale/hapticMale.glb
Then clear cache content (Developer > Network > Clear Disk Cache) and restart Interface, and repeat. You'll occasionally have Interface crash at start-up.
Testing:
- This PR should not crash at start-up because of that model.
- Blendshapes should still work. For example, using the following code in the JavaScript console should open and close the avatar's mouth per the blendshape value. (Edit the UUID to be that of the entity …
> Fix handling of missing glTF blendshape target meshes

- scripts/communityScripts/explore/explore.html
- scripts/communityScripts/explore/explore.js
The name field's label has been changed from "Domain Display Name" to "Location Name".
> Rename field in Explore app's "add location" dialog

- interface/resources/qml/hifi/tablet/ControllerSettings.qml
This enables the calibration for Vive Trackers on the Valve Index. I tested this on Debian Testing:
https://data.moto9000.moe/vircadia/%23808/tracker.webm
This should be done different as most HMDs can be used via OpenVR and could also be used with Vive Trackers because of that.
> Workaround: Add Valve Index to calibratable devices

- libraries/networking/src/DomainHandler.h
Figure it's better to change now before anyone starts using it. :) Noticed that I had missed it while documenting environment variables.
> Append 'Vircadia' to the environment variable for the metadata exporter port

- libraries/script-engine/src/ScriptEngine.cpp
I've confirmed this fixes the issue.
However, the original issue was reported by Twa_hinkle.
To test: Ensure the entity script server does not crash for any reason on start. An easy provable test is to add the Explore beacon to your domain and ensure the entity server script runs. Confirm your domain hows up in the Explore list.
> Prevent crash on entity-script-server due to logging interface.

- libraries/ui/src/OffscreenUi.h
Fixes a lot of:
warning: ‘constexpr QFlags<T>::QFlags(QFlags<T>::Zero) [with Enum = QFileDialog::Option; QFlags<T>::Zero = int QFlags<QFileDialog::Option>::Private::*]’ is deprecated: Use default constructor instead [-Wdeprecated-declarations]
There's going to be a bunch of these small ones, because it turns out not everything can be fixed to Qt 5.15's liking in a way that still compiles on old Qt versions. So I'll try to get in some small fixes that work on both versions first, and deal with the incompatible changes in a final PR.
> Qt 5.15 fixes: Initialize flags with default constructor

- interface/resources/qml/hifi/dialogs/security/Security.qml
In the Settings > Security dialog there is no longer a "Secure Transactions" section saying that your wallet is not set up and to open the Inventory app to get started.
This PR just hides this part of the dialog so that it is not displayed; no other code is changed.
> Hide "Secure Transactions" section in Settings > Security

- libraries/shared/src/LogHandler.cpp
- libraries/shared/src/LogHandler.h
This patch exposes some features of the logging system that were only available by tweaking the code, and adds the ability to use ANSI color, which seems to be available on all systems (Windows appears to have also added it).
This should make interesting messages much more distinctive. Example with color and milliseconds enabled:
Set `VIRCADIA_LOG_OPTIONS` to a string containing these keywords:
* color
* milliseconds
* process_id
* thread_id
Multiple options are comma separated. Example:
$ export VIRCADIA_LOG_OPTIONS="color,milliseconds"
> Improve logging: color, ms timestamps, PID, thread id via environment variable

- libraries/gl/src/gl/Config.cpp
- libraries/gl/src/gl/Config.h
- libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
- libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
- libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
- libraries/gpu/src/gpu/Texture.h
- libraries/render-utils/src/text/Font.cpp
This fixes the automatic texture memory size option.
In the original code, "auto" simply hard-codes texture size to 1 GB, and isn't "auto" whatsoever.
This PR implements 3 policies, with the one we use depending on what we can know:
* If we know how much VRAM is free (NVIDIA and ATI report this), then we query that. The code will then use available VRAM, leaving some amount (currently hardcoded as 64MB).
* If we don't know how much VRAM is free, but we do know how much there is in total, we set the limit to a percentage of that. This  happens on Intel. Currently the max use is hardcoded to 80%. The assumption here is that this is a low-spec machine, and unlikely to be running anything else at the same time, so we just need to leave some margin for system use.
* If we don't know anything, …
> Initial version of automatic texture memory size

- libraries/networking/src/FileResourceRequest.cpp
- libraries/networking/src/ResourceRequest.cpp
- libraries/networking/src/ResourceRequest.h
- libraries/script-engine/src/ScriptCache.cpp
- libraries/script-engine/src/ScriptCache.h
This PR helps ScriptCache detect local file changes.
Before, when working on local Client Scripts that rely on `Script.require` to load modules in, it was impractical to reload inner local module dependencies (without resorting to hacks like `Script.require('./file.js?'+Date.now())`).
With this PR, simply reloading a Client Script will pick up any local file changes automatically.
Note that I also considered just never caching local paths ever -- however, in my case URLs that look like local files might actually be across network shares; so, by actually checking the modification time here, ScriptCache continues to work well in those scenarios too. 
**Setup**: Create these two .js scripts in a local folder:
```js
// client-test.js
Script.require('./show-alert.js')
```
```js
// …
```
> ScriptCache: add local file change detection

- libraries/entities-renderer/src/EntityTreeRenderer.cpp
Fixes `enterEntity` and `leaveEntity` not firing in client entity script after doing Developer > Network > Reload Content.
> Fix enterEntity event not firing in entity script after content reload

- scripts/system/create/edit.js
- scripts/system/create/entityList/entityList.js
- scripts/system/create/entityList/html/entityList.html
- scripts/system/create/entityList/html/js/entityList.js
- scripts/system/create/entitySelectionTool/entitySelectionTool.js
- scripts/system/create/qml/EditTabView.qml
- scripts/system/create/qml/EditToolsTabView.qml
- scripts/system/html/css/edit-style.css
Contains:
1- **Entity List - Highlighting of the Last Selected entity**
The last selected entity is now displayed in darker blue in the list (if present per radius search)
This makes clearer which entity could become the parent.
2- Columns **visibility** and **order** are now **persistent**.
3- For clarity, "**Select Family**" and "**Select Top Family**" have been **renamed** respectively:
"**Select Parent And All Its Children**" and "**Select Top Parent And All Its Children**"
4- **New in-world bounding box color for a selected entity that is Parent & Child at the same time.**
When 1 entity is selected (in-world):
if the entity is a **Top Parent**, the selection color of the bounding box is **Orange**.
if the entity is **Parent and Child**, the selection color of the bounding box is …
> Create App. - Feature Bundle - Nov 2020

- .github/workflows/master_build.yml
Has no effect on PR builds.
Once merged, merges to master should start building. And should start building successfully once the following PR is merged: https://github.com/kasenvr/project-athena/pull/615
> Fix GHA master build target branch

- libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
GL_TEXTURE_FREE_MEMORY_ATI returns 4 values, not just 1.
This should fix a buffer overflow that happens on ATI cards, and hopefully avoid a crash on startup.
> Fix getting the free VRAM on ATI cards

- interface/src/main.cpp
Use the --forceCrashReporting command line parameter to have the crash handler launch regardless of what the internal setting says.
> Initial add of crash report arg option.

- libraries/gl/src/gl/GLWidget.cpp
- libraries/gl/src/gl/GLWidget.h
Deleted old GLWidget code that breaks alt which has been in use with Tivoli since September 17 without any issues. The problem is along the lines of the window menu bar capturing alt instead, which has long been fixed by Qt.
> Fix alt key on Linux

- .github/workflows/pr_build.yml
> Enable crash reporting on PR builds from GHA

- domain-server/resources/describe-settings.json
- domain-server/resources/web/js/shared.js
- domain-server/src/DomainServer.cpp
- domain-server/src/DomainServer.h
- libraries/networking/src/LimitedNodeList.cpp
This saves the IP and port to the domain server settings whenever a change is detected, then it will pull from settings to send these values in each metaverse heartbeat. It will also send one heartbeat at the time of a change in the IP address and port.
I believe that the bandwidth impact will be minimal for the domain-server side of things.
Also I believe I solved the bug where the automatic networking dropdown would not show.
The reason for this PR is because the metaverse server only gets an IP and port from the domain server in one packet and that is only when the domain server detects a change. If the metaverse server for any reason never got and saved that packet (through a bug or whatever) then the metaverse server will continue working with your Domain server and not have some …
> Send address and port with each metaverse heartbeat.

- libraries/entities-renderer/src/RenderableModelEntityItem.cpp
fixes #941 
caused by https://github.com/vircadia/vircadia/pull/830
Test plan:
- To test the model dimensions/collision bug fix, run this script: https://gist.githubusercontent.com/HifiExperiments/5b3a0207e222546b27ed182244a6861a/raw/cce164f967f7632cdccc845b75028e64ee1ef4ce/ModelTest.js
- turn on Show Bullet Collisions in Developer -> Physics
- Press `o` to toggle the modelURL. Verify that the dimensions and the collision shape are correct.
- for both models, confirm that modifying the dimensions/position/etc correctly updates the bullet physics
> Possible fix for bad physics performance

- hifi_vcpkg.py
Windows PR (and other) builds broke when Qt open source downloads stopped working for a while (see https://github.com/vircadia/vircadia/issues/976). The problem was that our VCPKG included only a single Qt URL for the JOM package. The second URL added in this PR is per the latest VCPKG source.
The new Windows VCPKG file referenced in this PR was created by downloading the current Windows VCPKG file, editing it, and zipping it back up.
For QA, just need a quick check that the PR's Windows build runs OK - Interface and server.
> Updated Windows VCPKG that includes an alternative JOM download URL

- libraries/shared/src/LogHandler.cpp
- libraries/shared/src/LogHandler.h
This helps with log flooding. Successive repeated log messages will be skipped and counted, the count will be output when a different message is logged.    
A new option of 'keep_repeats' has been added to `VIRCADIA_LOG_OPTIONS` to disable this.
Fixes #934
> Skip repeated log entries

- interface/src/AboutUtil.cpp
- interface/src/Bookmarks.cpp
- interface/src/avatar/AvatarPackager.cpp
- interface/src/scripting/AssetMappingsScriptingInterface.cpp
- interface/src/scripting/DesktopScriptingInterface.cpp
- interface/src/scripting/HMDScriptingInterface.cpp
- interface/src/scripting/WindowScriptingInterface.cpp
- interface/src/ui/ApplicationOverlay.cpp
- interface/src/ui/InteractiveWindow.cpp
- interface/src/ui/overlays/Overlays.cpp
- interface/src/ui/overlays/QmlOverlay.cpp
- libraries/ui/src/DockWidget.cpp
- libraries/ui/src/InfoView.cpp
- libraries/ui/src/OffscreenQmlElement.h
- libraries/ui/src/OffscreenUi.cpp
- libraries/ui/src/QmlFragmentClass.cpp
- libraries/ui/src/QmlWebWindowClass.cpp
- libraries/ui/src/QmlWindowClass.cpp
- libraries/ui/src/ui/TabletScriptingInterface.cpp
- plugins/openvr/src/OpenVrHelpers.cpp
fixes #810 
fixes #811 
Test plan:
- No change to normal builds
- If you build manually with QML disabled, run, and switch to VR, you should no longer crash
> Fix crashes when running with QML disabled in VR

- interface/resources/qml/controls/+webengine/FlickableWebViewCore.qml
- interface/resources/qml/controls/FlickableWebViewCore.qml
- interface/resources/qml/controls/TabletWebScreen.qml
- interface/resources/qml/controls/TabletWebView.qml
- interface/resources/qml/controls/WebView.qml
Any ideas on exactly what profiles were doing/how they were used? https://github.com/vircadia/vircadia/pull/988/files is where I made changes to it originally, I'm not entirely sure what the use of profiles are without an interceptor being needed to add to the user agent.
Was it that profiles are used to pass it on to new browser instances? But if that's the case, then can the webengine actually modify them? Is it needed to be an alias all the way down? Why not copy it from the bottom up one way?
I could also just manual put in the relevant profile pieces like I did for the FlickableCore, but then those are already there. So I'm not really sure.
EITHER WAY: this PR does solve the issue of the web views not working in all areas that I could effectively test.
NOTE: I was incorrect about my …
> Fix profile errors in QML. (also add FIXME's)

- libraries/entities-renderer/src/RenderableEntityItem.cpp
- libraries/entities-renderer/src/RenderableEntityItem.h
- libraries/entities-renderer/src/RenderableModelEntityItem.cpp
- libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
- libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
- libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
- libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
- libraries/entities-renderer/src/RenderableShapeEntityItem.h
- libraries/entities-renderer/src/RenderableTextEntityItem.cpp
- libraries/entities/src/EntityItem.cpp
- libraries/entities/src/EntityItem.h
- libraries/entities/src/EntityTreeElement.cpp
- libraries/entities/src/GizmoEntityItem.cpp
- libraries/entities/src/ModelEntityItem.cpp
- libraries/entities/src/ModelEntityItem.h
- libraries/entities/src/PolyVoxEntityItem.cpp
- libraries/entities/src/ShapeEntityItem.cpp
- libraries/render-utils/src/Model.cpp
- libraries/shared/src/SpatiallyNestable.cpp
- libraries/shared/src/SpatiallyNestable.h
fix #1039 
entities with billboardMode != NONE now use their local rotation for billboarding instead of their world orientation (which is affected by their parents)
Test plan:
- billboardMode should behave as it did before and nametags should work
> Fix rotation of billboarded entities with parents

- .gitignore
- assignment-client/src/AssignmentClient.cpp
- assignment-client/src/audio/AudioMixerSlavePool.cpp
- assignment-client/src/octree/OctreeServer.cpp
- domain-server/src/DomainServer.cpp
- interface/src/Application.cpp
- libraries/audio/src/AudioInjectorManager.cpp
- libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
- libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
- libraries/networking/src/ResourceManager.cpp
- libraries/networking/src/udt/SendQueue.cpp
- libraries/qml/src/qml/impl/SharedObject.cpp
- libraries/script-engine/src/ScriptEngine.cpp
- libraries/shared/src/GenericThread.cpp
- libraries/shared/src/SettingInterface.cpp
- libraries/shared/src/ThreadHelpers.h
- libraries/ui/src/ui/TabletScriptingInterface.cpp
- plugins/openvr/src/OpenVrDisplayPlugin.cpp
- plugins/openvr/src/ViveControllerManager.cpp
this will hopefully help with debugging.  in VS, when you hit a breakpoint or pause execution (or crash), in the Thread dropdown, more threads will have descriptive names now.  there's still a lot of unnamed ones...I think some are from the QThreadPool, and evidently you can't name them because there's no way to name a thread multiple times (when they get reused).  a bunch are seemingly from web processes...and there's a bunch that I'm not sure what they do...
Test plan:
- no real functional change, make sure server and client both still work
> Name a bunch of threads

- scripts/system/create/assets/data/createAppTooltips.json
fix https://github.com/vircadia/vircadia/issues/1060
> Fix tooltips

- libraries/animation/src/AnimInverseKinematics.cpp
- libraries/animation/src/AnimSkeleton.cpp
- libraries/animation/src/AnimSkeleton.h
How to repro?
Use this avatar http://animedeck.com/cdn/avatars/kalila/avatarUnlit.fst?432 and go into VR. The moment the controllers turn on, the IK system will crash.
I personally tested this with a Valve Index but it's possible it will happen with any set of controllers.
> Fix AnimInverseKinematics crash

- libraries/entities/src/EntityItem.cpp
- libraries/entities/src/ZoneEntityItem.cpp
- libraries/physics/src/ShapeFactory.cpp
- libraries/shared/src/ShapeInfo.cpp
- scripts/system/create/entityProperties/html/js/entityProperties.js
- scripts/system/create/modules/entityShapeVisualizer.js
fix https://github.com/vircadia/vircadia/issues/172
which zones you are in is determined by `EntityTreeRenderer::findBestZoneAndMaybeContainingEntities`, which first calls `evalEntitiesInSphere` (which does a rough bounding box/sphere check) and then, under certain circumstances, calls `contains` on each of those entities to make sure we're actually inside them.  however, when a zone's visibility or transform is edited, we also immediately call `EntityTreeRenderer::LayeredZones::update`, which calls `contains` on the zone (not `evalEntitiesInSphere`).  `EntityItem::contains` was wrong for this case, so it would improperly return `true` when you were in the corner, but then next frame, when we call `evalEntitiesInSphere`, it would remove the zone before `contains` could be called.  this …
> Non-uniformly scaled sphere zones and models behave like ellipsoids (and fix EntityItem::contains sphere case)

- interface/src/ui/PreferencesDialog.cpp
Changed two occurrences of "High Fidelity" to "Vircadia".
> Fix privacy setting text

- BUILD_LINUX.md
This workaround seems to have been unnecessary for years, as we build nvtt ourselves via vcpkg.
> Remove nvtt workaround from linux build docs

- libraries/controllers/src/controllers/InputDevice.h
- libraries/controllers/src/controllers/ScriptingInterface.cpp
- libraries/controllers/src/controllers/ScriptingInterface.h
- libraries/controllers/src/controllers/UserInputMapper.cpp
- libraries/controllers/src/controllers/UserInputMapper.h
- libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
- libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
- libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp
- plugins/hifiSdl2/src/Joystick.cpp
- plugins/hifiSdl2/src/Joystick.h
- plugins/oculus/src/OculusControllerManager.cpp
- plugins/oculus/src/OculusControllerManager.h
- plugins/openvr/src/ViveControllerManager.cpp
- plugins/openvr/src/ViveControllerManager.h
inspired by @daleglass's FOSDEM talk, I've been meaning to change this for a while
Test plan:
- no real functional change
- make sure you can still trigger a haptic pulse on existing hand controllers, for example: `Controller.triggerHapticPulse(0.5, 10, 2);` should trigger a pulse on both hands
> triggerHapticPulse supports arbitrary device index instead of just two hands

- libraries/networking/src/ResourceCache.cpp
When a Resource is requested from qrc://, the Resource::handleDownloadProgress
event is never called, and therefore _bytesTotal remains at zero. This confuses
ResourceCache later, which has a sanity check that doesn't pass when resources
are retrieved, yet no data accumulates.
Fixes #1065
> Set resource total size to content size when using a qrc:// resource

- scripts/communityScripts/chat/FloofChat.js
This helps to prevent chat spam when a large amount of people are in a domain. Further improvements and overhauls will be done to the chat on this feature and many others when a new chat client is created.
> Domain chat muted by default

- assignment-client/src/messages/MessagesMixer.cpp
- assignment-client/src/messages/MessagesMixer.h
- domain-server/resources/describe-settings.json
This PR will stop sending messages for nodes that surpass a certain amount of messages within one second. Currently the default is 1000 messages per second meaning you'd have to send an average of 1 message per millisecond to hit the limit, so under normal usage without knowledge of this setting... you will be unlikely to have this be an issue.
Future to-do: figure out a way to log messages in a performant way about the node going over the limit (spamming). 
Question: Does the repeated log entry thing work with this so if 1000 messages piled up in a second, only a chunk of them will actually see the light? Is that pretty performant...?
To test:
1. Go to your domain server settings, scroll to the `Messaging Mixer` area and set `Per-Node Send Messages` to something low like 2.
2. Connect to …
> Add messaging mixer rate limiting per node functionality.

- interface/resources/qml/hifi/audio/Audio.qml
Fixes repeated QML errors in program log after using the Settings > Audio dialog.
> qrc:/qml/hifi/audio/Audio.qml: ReferenceError: AudioScriptingInterface is not defined
> Fix program log spam after using Audio dialog

- interface/src/Menu.cpp
- interface/src/Menu.h
- interface/src/avatar/MyAvatar.cpp
- interface/src/avatar/MyAvatar.h
- interface/src/ui/PreferencesDialog.cpp
- libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
- libraries/avatars/src/AvatarData.cpp
- libraries/physics/src/CharacterController.cpp
This PR consists of small optimisations and tidying of things that were noticed in passing, related to `MyAvatar`.  No behaviour should change.
1. Removed the "Toggle Hips Following" option from the Developer menu.  It had no effect on any code.
2. The deprecated `MyAvatar.setToggleHips` script function, which had no effect on any code, now ouptuts a log warning indicating that it's deprecated.
3. In `CharacterController::applyMotor`, prevented unnecessary calls to `btVector3::rotate()` when the motor has no rotation.  This change also improves readability through the use of clearly-named lambdas.
4. In `AvatarData::getFauxJointIndex`, prevented unnecessary string comparisons when the named joint is a real joint rather than a faux one.
5. In `Avatar::getJointIndex`, removed an unnecessary …
> Small optimisations and tidying related to MyAvatar

- libraries/baking/src/TextureBaker.cpp
- libraries/entities-renderer/src/RenderableImageEntityItem.cpp
- libraries/entities/src/EntityItemProperties.cpp
- libraries/entities/src/ImageEntityItem.cpp
- libraries/entities/src/ImageEntityItem.h
- libraries/gpu/src/gpu/Texture.h
- libraries/gpu/src/gpu/Texture_ktx.cpp
- libraries/image/src/image/TextureProcessing.cpp
- libraries/image/src/image/TextureProcessing.h
- libraries/material-networking/src/material-networking/KTXCache.cpp
- libraries/material-networking/src/material-networking/TextureCache.cpp
- libraries/material-networking/src/material-networking/TextureCache.h
fix https://github.com/vircadia/vircadia/issues/697
before, keepAspectRatio only worked if the entity dimensions were 1x1.  now, if keepAspectRatio is true, the image will properly fit into its bound no matter what they are.  additionally, image entities now have naturalDimensions.
I couldn't reproduce the part of the bug about keepAspectRatio not working for pngs.
one open question: when a sub image is selected, should it respect the aspect ratio of the original image, or the aspect ratio of the sub image?  it's hard for me to tell which is the correct behavior
Test plan:
- for a variety of images, edit them in create
- confirm that when keepAspectRatio is false, they behave as before, and completely fill their bounds
- confirm that when keepAspectRatio is true, they always show at their …
> Image Entities: fix keepAspectRatio, implement naturalDimensions

- libraries/fbx/src/GLTFSerializer.cpp
- libraries/fbx/src/GLTFSerializer.h
Implements support for glTF normalized values.
Testing:
- Per https://github.com/vircadia/vircadia/issues/957.
- Domains' content not broken.
> Fix glTF vertex colors

- libraries/entities-renderer/src/RenderableModelEntityItem.cpp
This fixes a stack-use-after-return error in RenderableModelEntityItem.
Fixes #1128
> Capture by value rather than by reference in RenderableModelEntityItem

- libraries/script-engine/src/ScriptsModel.h
Fixes #1131, possibly solves a crash on exit.
See https://www.geeksforgeeks.org/virtual-destructor/ for an explanation of why this is necessary.
Testing:
Testing is only properly possible with #1127 applied, but since the change is so simple this should be entirely harmless in any case.
> Add virtual destructor to TreeNodeBase

- libraries/entities-renderer/src/RenderableEntityItem.h
- libraries/render-utils/src/MeshPartPayload.h
Possible fix for "Avatar pieces rotate in an incorrect offset sometimes", https://github.com/vircadia/vircadia/issues/1026 .
The easiest way I found of reproducing the problem was to clear cache and start up in a heavy domain while rotting avatar with keyboard and/or right-mouse-press-and-drag. Then, if the problem didn't occur, teleport to another heavy domain and immediately quit Interface. Then start up again there. ... and so on.
> Fix avatar parts rotating

- libraries/entities-renderer/src/RenderableTextEntityItem.h
- libraries/networking/src/PacketReceiver.h
Fixes warnings like:
```
/libraries/entities-renderer/src/RenderableTextEntityItem.h:47:18: warning: ‘virtual bool render::entities::TextEntityRenderer::needsRenderUpdate() const’ can be marked override [-Wsuggest-override]
47 |     virtual bool needsRenderUpdate() const;
|                  ^~~~~~~~~~~~~~~~~
```
> Add missing override keywords.

- libraries/entities/src/ShapeEntityItem.cpp
It declared a variable it didn't use, and instead used the unlocked version.
> Fix ShapeEntityItem::getRotateForPicking()

- domain-server/src/DomainServer.cpp
- domain-server/src/DomainServer.h
- libraries/embedded-webserver/src/HTTPConnection.h
The domain server currently doesn't log any information regarding the access to the management interface. This PR fixes that.
It adds access logging in the `vircadia.domain_server.auth` logging category. Example output:
"OPEN ACCESS" here means the server has no password set, and anyone can have unauthenticated access:
```
[04/03 15:57:59] [WARNING] [vircadia.domain_server.auth] "127.0.0.1" - OPEN ACCESS - "GET"   QUrl("/nodes.json")
[04/03 15:57:59] [WARNING] [vircadia.domain_server.auth] "127.0.0.1" - OPEN ACCESS - "GET"   QUrl("/assignments.json")
```
Basic auth was required but none was provided:
```
[04/03 17:33:54] [WARNING] [vircadia.domain_server.auth] "127.0.0.1" - Basic auth required - "GET"   QUrl("/")
```
Auth was provided for 'admin', but either the username or the password …
> Log authentication events in the domain server

- libraries/networking/src/NetworkingConstants.h
Per the version in Qt 5.15.2's \qtwebengine\tools\scripts\version_resolver.py.
The new version should be reported in the default browser string in a Web entity, for example.
> Update browser Chrome version

- libraries/gpu-gl/CMakeLists.txt
This should have no actual effect, just a warning fix. Fixes:
```
CMake Warning (dev) in libraries/gpu-gl/CMakeLists.txt:
A logical block opening on the line
/home/dale/git/vircadia/vircadia-master/libraries/gpu-gl/CMakeLists.txt:4 (if)
closes on the line
/home/dale/git/vircadia/vircadia-master/libraries/gpu-gl/CMakeLists.txt:6 (endif)
with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
This one snuck into PR #1149
> Fix mismatched if in CMake warning

- libraries/networking/src/FingerprintUtils.cpp
Now all the fingerprints are hashed. This has the following benefits:
* It doesn't expose raw system IDs. The actual ID is hashed with a value unique to Vircadia, so that it won't match any other identifier. This slightly improves privacy, since it won't be possible to match the fingerprint with any other service.
* It should be more future-proof. Apple doesn't promise that the platform ID will have any particular format. The hashing means it doesn't matter if it stops being a valid UUID at some point.
Testing of this is needed on Windows and OSX.
Testing procedure:
1. Connect to a domain with a previous client. Note the machine fingerprint being mentioned in the logs, eg:
`Mar 25 19:34:43 hub.daleglass.net domain-server[795]: [03/25 19:34:43] [DEBUG] [default] Allowed connection from …
> Hash Windows and Mac machine fingerprints.

- cmake/macros/MemoryDebugger.cmake
Only supported starting from VS2019 v16.9.
Only the address sanitizer is supported, as MS has not implemented any others yet.
Testing plan:
* Ensure Visual Studio is VS 2019, v16.9.
* Set the environment variable  `VIRCADIA_MEMORY_DEBUGGING=1`
* Run CMake, compile
* Verify that there is no compile failure
* Verify that `/fsanitize=address` is passed to the compiler (if possible)
* Run the program. Check if there are any messages on the output from the sanitizer. The "Developer/Crash/Double Free" menu option should trigger it if nothing shows up.
It should also be possible to build on Windows using Clang, which supports more functionality. MSVC only has the address sanitizer, while Clang also detects undefined behavior.
> Implement VIRCADIA_MEMORY_DEBUGGING for Windows

- tools/nitpick/CMakeLists.txt
Request by veridian on Discord: link to pthread last
I tried on my Linux install and it works the same both ways. So this needs somebody to test it and see what problem it fixes and that it really does fix it.
> Link to pthread last

- domain-server/src/DomainServer.cpp
- libraries/networking/src/udt/PacketHeaders.cpp
- libraries/networking/src/udt/PacketHeaders.h
- tools/dissectors/1-hfudt.lua
Given the following:
- Any addition or removal of packet types will generally require a protocol bump.
- Adding a new packet type will add it to the end of the list (in PacketHeaders.h), taking the value one larger than the previous largest packet type
- Removing a packet type (in theory) will renumber all of the following packet types
- Detection of a protocol mismatch is done through PacketType "DomainConnectRequest", which has a Packet Type ID of 31.
- StunResponse (ID=1) is no longer in use (as of df47f1dd0bbfbfa54c51f5fa913c91c9d5851f14 )
Proposed:
- Rename StunResponse to DomainConnectRequestNew and have servers immediately begin treating it the same as DomainConnectRequest
- At some point swap the codes so interfaces will start using ID=1 to connect rather than ID=31
- This will …
> The domain server should see Packet ID=1 as a (broken) attempt to connect to the domain server

- BUILD.md
- BUILD_OSX.md
- BUILD_WIN.md
This PR fixes the non-consecutive header level increases in the build docs since that doesn't work in Sphinx and throws warnings.
> Fix non-consecutive header level increases in build docs

- .gitmodules
- CMakeLists.txt
The Vircadia Web app is included in the Vircadia repository as a Git submodule. In particular, this enables code searches to include both Vircadia and Vircadia Web app files.
Additionally:
- Vircadia Web app files are listed in the IDE tree.
- HTML, CSS, and other files in the JavaScript directories are included in the IDE tree in addition to JavaScript files.
Note: The Vircadia Web app is NOT included in PR or release builds.
> Include Vircadia Web app as a Git submodule

- .github/workflows/master_build.yml
Tested in PR https://github.com/vircadia/vircadia/pull/1197 by changing the target branch from `master` to `merge-test`. The resulting merge-to-master GHA build successfully build MacOS: https://github.com/vircadia/vircadia/actions/runs/804058921
> Fix GitHub Actions merge-to-master MacOS build

- tools/qt-builder/patches/qt5.15-gcc11.patch
gcc11 is requires `#include <limits>` in places previous versions didn't.
This makes Qt 5.15.2 build on Fedora 34, and this should also extend to other recent Linux distros.
> Add patch for building Qt 5.15 on gcc11

- .grenrc.js
You can read more about it here: https://github.com/github-tools/github-release-notes
I am going to add this to our other repositories as well so that I can generate changelogs for release notes from each pull request.
You can see an example of how the output ends up looking here: https://github.com/vircadia/vircadia-docs-sphinx/pull/154/files?short_path=880352b#diff-880352b5c67c6cde1551356bcfb4055537afbeef3be4cfa51cf4e1a11e983e2f
> Add "gren" configuration for easy changelog generation

- domain-server/src/DomainServer.h
Missed from https://github.com/vircadia/vircadia/pull/1219.
> Conditionally include WebRTCSignalingServer.h

- cmake/ports/draco/portfile.cmake
The previous version breaks on Fedora 34, and likely other distros with recent compilers due to not including `cstddef` and `limits` headers.
This is already fixed upstream, but only in master. And looking at google/draco#704 there may be compatibility issues with using the latest code.
So for now we're upgrading from 1.3.3 to 1.3.6 and adding the fix.
The fix is already in https://github.com/vircadia/draco/tree/1.3.6-fixed
Testing plan:
* Build
* Verify that cmake runs successfully to completion
* Check that this runs on all operating systems.
In principle this should be a completely harmless change, since it only adds additional header includes. There might be some sort of issue arising from the upgrade to 1.3.6, in which case we could stick with 1.3.3.
> Fix draco compilation on gcc11

- libraries/script-engine/src/ScriptEngine.cpp
- libraries/script-engine/src/ScriptEngine.h
- libraries/script-engine/src/ScriptEngines.cpp
This PR drops all remaining references to QScriptEngineDebugger.
It appears that this *used* to be available by holding down [Shift] while launching Vircadia but this feature was disabled due to launching deadlocks.  This appears to currently still be available by sticking #debug at the end of a scripting URL.
I have verified that this compiles and links but have not attempted to run or verify that scripts are running properly.
> drop remaining references to QScriptEngineDebugger

- libraries/script-engine/src/WebSocketClass.cpp
All other callbacks are documented as "Called ...". ("Triggered ..." is for signals.)
> Fix typo in WebSocket~onMessageCallback API documention.

- cmake/ports/webrtc/CONTROL
- cmake/ports/webrtc/README.md
- cmake/ports/webrtc/copy-VCPKG-file-win.cmd
- cmake/ports/webrtc/portfile.cmake
- libraries/audio-client/src/AudioClient.cpp
- libraries/audio-client/src/AudioClient.h
- libraries/shared/src/shared/WebRTC.h
- Updates the WebRTC version used on Windows from version M81 to M84.
- Adds WebRTC data channel to the WebRTC VCPKG. *
`*` In current `master`, the audio component of WebRTC is used for echo cancellation.
Check that the following audio features continue to work on Windows:
Check that other OSes continue to work:
(Resubmission of PR https://github.com/vircadia/vircadia/pull/1221.)
> Update WebRTC Windows package

- scripts/system/create/entityProperties/html/js/entityProperties.js
- scripts/system/html/css/edit-style.css
**HMD Compliant Zone Selector for "renderWithZones"**
This PR modify the Zone Selector used for "**renderWithZones**" property in the Create Application that wasn't working in HMD.
It no more rely on a dropdown, but on a scrollable zone selector composed of buttons:
This was among the last things in the Create app. that requires that we remove our VR helmet to work in-world.  _(Outside maybe to be able to paste stings in textbox in HMD)_
This also make room for additional button for future development (eventual functions for bulk zone selections)
> Make Zone Selector for "renderWithZones" in "Create" app HMD Compliant.

- plugins/hifiLeapMotion/CMakeLists.txt
It doesn't have many users, and causes an annoying 'LEAPMOTIONConfig.cmake' not found error if the SDK isn't installed.
We now require running cmake with -DUSE_LEAPMOTION=1 to enable using it.
This replaces:
```
CMake Warning at /home/dale/vircadia-files/vcpkg/2a0d2829/scripts/buildsystems/vcpkg.cmake:262 (_find_package):
By not providing "FindLEAPMOTION.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"LEAPMOTION", but CMake did not find one.
Could not find a package configuration file provided by "LEAPMOTION" with
any of the following names:
LEAPMOTIONConfig.cmake
leapmotion-config.cmake
Add the installation prefix of "LEAPMOTION" to CMAKE_PREFIX_PATH or set
"LEAPMOTION_DIR" to a directory containing one of the above files.  If …
```
> Don't use LeapMotion by default.

- cmake/modules/FindGifCreator.cmake
This fixes this:
```
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
The package name passed to `find_package_handle_standard_args` (GIFCREATOR)
does not match the name of the calling package (GifCreator).  This can lead
to problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
cmake/modules/FindGifCreator.cmake:24 (find_package_handle_standard_args)
/home/dale/vircadia-files/vcpkg/2a0d2829/scripts/buildsystems/vcpkg.cmake:262 (_find_package)
interface/CMakeLists.txt:487 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> Fix CMake GifCreator name warning

- cmake/ports/nvtt/portfile.cmake
Well, this is a weird one.
Turns out that nvtt already has a MacOS specific path, which includes the needed header... but it's not being taken for some reason.
This is just a brute force fix, since the project is dead anyway.
> Fix for nvtt on MacOS

- tools/doxygen/Doxyfile
Makes Doxygen output only warnings and errors - i.e., not all the files it's successfully processed.
> Quiet Doxygen output

- .github/workflows/master_build.yml
- .github/workflows/pr_build.yml
This PR disables cloning submodules in the GitHub Actions builds.
The vircadia-web submodule isn't used as far as I can tell and not only wastes resources but also makes it more annoying to test GitHub Actions in ones own repository.
> GitHub Actions do not clone submodules

- .github/stale.yml
Stale bot will no longer close issues and the comment has been made more "human".
The days to stale has have been moved from 120 days to 180 days.
> Reduce stale-bot's aggressiveness.

- interface/src/Application.cpp
- interface/src/main.cpp
- interface/src/scripting/WindowScriptingInterface.cpp
- libraries/networking/src/AddressManager.cpp
- libraries/networking/src/AddressManager.h
- libraries/networking/src/DomainHandler.cpp
- libraries/networking/src/DomainHandler.h
- libraries/networking/src/NetworkingConstants.h
- libraries/networking/src/NodeList.cpp
- libraries/script-engine/src/ScriptEngine.cpp
To test... 
Open the console with Ctrl + Alt + J.
1. Using the `AddressManager.handleLookupString` API, try every type of possible path/URL. Especially try a placename with spaces in it.
2. Try all attempts with and without "hifi://".
Closes #1242
> Add ability for 'handleLookupString' to have spaces.

- .github/workflows/pr_build.yml
When CMake calls vcpkg, if something goes wrong in that part of the process, it points to a path with a log file.
On GHA this doesn't help much, as the log files aren't accessible. This PR creates an archive with everything that looks like a log under the vcpkg directory, so that it can be used for troubleshooting.
This should be particularly helpful for Mac OS builds, since not a lot of people have the hardware for it.
> Archive cmake logs, for debugging

- CMakeLists.txt
This fixes this:
```
1> [CMake] Writing cmake config to C:/Users/Builder/source/repos/vircadia/out/build/x64-Debug\vcpkg.cmake
1> [CMake] -- C:/Users/Builder/source/repos/vircadia/out/build/x64-Debug/qt.cmake included!
1> [CMake] CMake Error at C:\Users\Builder\Source\Repos\vircadia\CMakeLists.txt:121 (project):
1> [CMake]   Generator
1> [CMake] 
1> [CMake]     Ninja
1> [CMake] 
1> [CMake]   does not support toolset specification, but toolset
1> [CMake] 
1> [CMake]     host=x64
1> [CMake] 
1> [CMake]   was specified.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Configuring incomplete, errors occurred!
```
It happens when trying to build by using VS Community's internal cmake support. It's Windows specific because the toolset setting happens within a Windows-specific branch.
This doesn't fix …
> Fix "Ninja does not support toolset specification" on Windows

- android/apps/interface/src/main/cpp/native.cpp
- libraries/controllers/src/controllers/UserInputMapper.cpp
- tools/ac-client/src/ACClientApp.cpp
- tools/atp-client/src/ATPClientApp.cpp
- tools/ice-client/src/ICEClientApp.cpp
- tools/nitpick/src/TestCreator.cpp
- tools/skeleton-dump/src/SkeletonDumpApp.cpp
- tools/vhacd-util/src/VHACDUtilApp.cpp
This fixes a whole bunch of these:
```
In file included from /usr/include/qt5/QtCore/QTextStream:1,
from /home/dale/git/vircadia/vircadia-master/tools/nitpick/src/AWSInterface.h:18,
from /home/dale/git/vircadia/vircadia-master/tools/nitpick/src/TestCreator.h:21,
from /home/dale/git/vircadia/vircadia-master/tools/nitpick/src/TestCreator.cpp:10:
/usr/include/qt5/QtCore/qtextstream.h:293:75: note: declared here
293 | Q_CORE_EXPORT QT_DEPRECATED_VERSION_X(5, 15, "Use Qt::endl") QTextStream &endl(QTextStream &s);
|            ```
> Replace uses of endl on Qt classes with Qt::endl

- interface/src/Application.cpp
- libraries/entities/src/EntityTree.cpp
- libraries/networking/src/AssetResourceRequest.cpp
- libraries/render-utils/src/Model.cpp
- libraries/script-engine/src/ScriptEngine.cpp
- libraries/shared/src/shared/FileUtils.cpp
Fixes a bunch of this:
`‘QStringList QString::split(const QRegExp&, QString::SplitBehavior) const’ is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]`
> Fix QString::SplitBehavior deprecation, replace with Qt::

- interface/CMakeLists.txt
This should have no effect on Unix, but fix the resource issue on Win32.
This fixes #1308
> Copy resources to interface's exe directory

- interface/src/Application.cpp
A trivial Qt warning fix.
Thought there would be more of these, only found one.
> Fix QDir::operator= is deprecated

- scripts/system/bubble.js
Adds an menu item in "Settings" to toggle the HUD shield/bubble button on or off.
Shield button remains available in the tablet or toolbar, it is called "HUD shield button" but suggestions are welcome
fixes https://github.com/vircadia/vircadia/issues/1210 but makes it optional.
> make HUD bubble/shield button optional

- scripts/system/create/edit.js
- scripts/system/create/entityProperties/html/js/entityProperties.js
- scripts/system/html/css/edit-style.css
This PR add a "Reset Rotation" to the properties tab
By clicking on the button, the "rotation" or "localRotation" get reset to (0,0,0).
If the entity doesn't have a parent, it will reset the rotation.
If the entity have a parent, it will reset the "localRotation" if the mode is "Local" or the "rotation" if the mode is "World".
The button is only effective for a single selection, as the "Copy Rotation" and "Paste Rotation" buttons are.
-----
I hesitated to pull this code, thinking that it is a bit over-design. But since I find my-self starting to use it, then I think it can be useful to some people.
I will let you decide about the fate of this pull request. Personally, I will be fine with or without it.
> Create app - "Reset Rotation" button

- assignment-client/src/AssignmentClient.cpp
- assignment-client/src/AssignmentClient.h
- assignment-client/src/AssignmentClientMonitor.cpp
- domain-server/src/DomainServer.cpp
- domain-server/src/DomainServer.h
- ice-server/src/IceServer.cpp
- libraries/networking/src/BaseAssetScriptingInterface.cpp
- libraries/networking/src/LimitedNodeList.cpp
- libraries/networking/src/LimitedNodeList.h
- libraries/networking/src/NetworkPeer.cpp
- libraries/networking/src/Node.cpp
- libraries/networking/src/NodeList.cpp
- libraries/networking/src/NodeList.h
- libraries/networking/src/NodeType.h
- libraries/networking/src/udt/NetworkSocket.cpp
- libraries/networking/src/udt/NetworkSocket.h
- libraries/networking/src/udt/PacketHeaders.h
- libraries/networking/src/udt/Socket.cpp
- libraries/networking/src/udt/Socket.h
- libraries/networking/src/webrtc/WebRTCDataChannels.cpp
- libraries/networking/src/webrtc/WebRTCDataChannels.h
- libraries/networking/src/webrtc/WebRTCSocket.cpp
- libraries/networking/src/webrtc/WebRTCSocket.h
- Web SDK connections to assignment clients: Individual WebRTC data channel connections to each assignment client, with WebRTC signaling routed via the domain server.
- Protocol change: New "WebRTC signaling" packet used between the domain server and assignment clients to exchange user client WebRTC signaling messages relayed to assignment clients via the domain server.
Works in conjunction with Web SDK PR: https://github.com/vircadia/vircadia-web-sdk/pull/25
QA: See the Web SDK PR.
> Assignment client WebRTC connections

- libraries/physics/src/MultiSphereShape.cpp
Some avatar geometries trigger this crash:
```
Exception thrown: read access violation.
**radius** was nullptr.
>	interface.exe!MultiSphereShape::calculateSphereLines(std::vector<std::pair<glm::vec<3,float,0>,glm::vec<3,float,0>>,std::allocator<std::pair<glm::vec<3,float,0>,glm::vec<3,float,0>>>> & outLines, const glm::vec<3,float,0> & center, const float & radius, const int & subdivisions, const glm::vec<3,float,0> & direction, const float & percentage, std::vector<glm::vec<3,float,0>,std::allocator<glm::vec<3,float,0>>> * edge) Line 593	C++
interface.exe!MultiSphereShape::calculateChamferBox(std::vector<std::pair<glm::vec<3,float,0>,glm::vec<3,float,0>>,std::allocator<std::pair<glm::vec<3,float,0>,glm::vec<3,float,0>>>> & outLines, const std::vector<float,std::allocator<float>> & …
```
> Fix avatar crash

- pkg-scripts/README.md
- pkg-scripts/make-deb-server
This patch is in response to errors creating .DEB package files, due to the change in location for qt5 libraries.
Some attempt has been made to detect and handle system-qt compilations, but as this was not one of them (did someone post a list of the required packages to install somewhere?) this has not been tested.
make-rpm-server has not been tested either but likely requires similar changes to compensate for the new library location.
> Get make-deb-server working again

- libraries/entities/src/EntityItemProperties.cpp
Adjustment to Doc for "created" properties.
The doc was pretending that it is a string value but it's in fact a number (Unix Timestamp).
Addressing ISSUE #839
> Adjustment to Doc for "created" properties

- assignment-client/src/audio/AvatarAudioStream.h
- interface/src/avatar/MyHead.h
- libraries/animation/src/AnimNodeLoader.h
- libraries/animation/src/AnimRandomSwitch.h
- libraries/animation/src/AnimStateMachine.h
- libraries/audio/src/AudioInjectorManager.h
- libraries/audio/src/InjectedAudioStream.h
- libraries/avatars/src/AvatarData.h
- libraries/avatars/src/HeadData.h
- libraries/networking/src/AccountManager.h
- libraries/networking/src/NLPacketList.h
- libraries/networking/src/Node.h
- libraries/networking/src/NodeList.h
- libraries/networking/src/udt/CongestionControl.h
- libraries/networking/src/udt/ControlPacket.h
- libraries/networking/src/udt/PacketList.h
- libraries/networking/src/udt/SendQueue.h
- libraries/shaders/src/shaders/Shaders.h
- libraries/ui/src/VrMenu.cpp
This attempts to find and replace most instances of "do not copy this class" code with Q_DISABLE_COPY.  This:
* standardizes the code,
* ensures that both the copy constructor and assignment operator are handled,
* ensures use of the newer "= delete" syntax
There are a few places that I did not replace the code:
* Two classes didn't obviously #include QObject (which defines Q_DISABLE_COPY) or didn't appear intended to, and
* What the heck is happening with interface/src/avatar/MyHead.h, is this a typo or bug in the code?
Testing focus:
* NONE - these changes should not have any effect outside of the compiler
> Code Review: use of Q_DISABLE_COPY.

- plugins/pcmCodec/CMakeLists.txt
- plugins/pcmCodec/src/PCMCodecManager.h
Fixes #1364
As explained in the bug above, when the PCM or zlib plugins detect a missing audio packet, they create a zero-sized buffer that trips up an assertion check.
> Fix crash due to audio packet loss with PCM and zlib codecs.

- interface/src/Application.h
- interface/src/graphics/GraphicsEngine.h
- interface/src/ui/overlays/Overlays.h
- libraries/display-plugins/src/display-plugins/CompositorHelper.h
- libraries/entities/src/EntitySimulation.h
- libraries/networking/src/HMACAuth.h
- libraries/octree/src/OctreeEditPacketSender.h
- libraries/physics/src/PhysicalEntitySimulation.h
- libraries/render-utils/src/Model.h
- libraries/shared/src/DependencyManager.h
This fixes around 1700 warnings.
> Replace the deprecated QMutex{ QMutex::Recursive} with QRecursiveMutex (solves approximately 1700 warnings).

- libraries/embedded-webserver/src/HTTPManager.cpp
At least on Linux, the current domain web page fails to work properly due to the embedded webserver using the wrong mime type:
```
$ wget http://localhost:40100
--2021-11-03 01:07:39--  http://localhost:40100/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:40100... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:40100... connected.
HTTP request sent, awaiting response... 302 Found
Location: /web-new/dist/spa/index.html#wizard [following]
--2021-11-03 01:07:39--  http://localhost:40100/web-new/dist/spa/index.html
Connecting to localhost (localhost)|127.0.0.1|:40100... connected.
HTTP request sent, awaiting response... 200 OK
Length: 959 [application/x-extension-html]
Saving to: ‘index.html.1’
index.html.1 …
```
> Fix mime type for serving .htm and .html files with the embedded webserver.

- cmake/macros/TargetOpenSSL.cmake
- ice-server/CMakeLists.txt
- launchers/qt/CMakeLists.txt
Earlier versions don't work with WebRTC, and cause linking errors.
OpenSSL 1.1 is supported in Ubuntu 18.04, although 1.0 can still be installed, which will cause the build to fail. This change ensures the issue is detected right in cmake rather than having the build explode later.
Testing:
Test on Ubuntu 18.04, with OpenSSL 1.0 installed (`libssl1.0-dev` present, `libssl-dev` not present)
Before this change, cmake will say something like:
```
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2n")  
```
and the build will probably fail with:
```
../libraries/networking/libnetworking.so: undefined reference to `BIO_meth_new'
../libraries/networking/libnetworking.so: undefined reference to `OPENSSL_init_crypto'
../libraries/networking/libnetworking.so: undefined reference to …
```
> Require OpenSSL 1.1.0 during CMake.

- scripts/system/create/entityList/entityList.js
In the Entity List, there is a column to indicate the presence of script on an entity.
_Before that modification, it was only present for entities having a Client Script._
**Now** it will be present if there is a **Client OR Server** script.
> Create app: Script indicator toggles for both entity client & server scripts.

- libraries/render-utils/src/Model.cpp
See the comment in the code for a detailed discussion of the issue. This is
a workaround, but it should be a safe one.
Testing:
It is not known what causes the issue to happen, but it may be related to avatars. It seems to mostly happen at login, or when teleporting into a different region. It seems to happen more often with more avatars in the region.
Look for a warning:
`_meshStates has N items when it should have none. Model with URL...` in the logs. So far in my testing I've not managed to trigger it, so if it happens during testing please paste the output in a comment. The intention is to make the warning useful enough to locate whatever is having a problem, but I'm not yet sure if the logged information is going to be helpful and/or accurate.
Closes #958
> Fix for _meshStates.empty() assertion.

- interface/src/ModelPackager.cpp
- interface/src/ModelPackager.h
- interface/src/ui/Stats.cpp
- libraries/model-networking/src/model-networking/ModelCache.cpp
- libraries/model-serializers/src/FBXSerializer.cpp
- libraries/model-serializers/src/FST.cpp
- libraries/model-serializers/src/FST.h
- libraries/model-serializers/src/FSTReader.cpp
- libraries/model-serializers/src/FSTReader.h
- libraries/model-serializers/src/GLTFSerializer.cpp
- libraries/networking/src/ResourceCache.cpp
- libraries/networking/src/ResourceCache.h
- libraries/script-engine/src/ScriptEngines.cpp
- libraries/script-engine/src/ScriptEngines.h
- libraries/shared/src/HifiConfigVariantMap.cpp
- libraries/shared/src/shared/HifiTypes.h
- libraries/task/src/task/Config.h
This replaces those uses with QMultiHash and QMultiMap. This removes a fair amount of warnings. Only 157 to go.
> Fix deprecated usage of multiple keys in QHash and QMap.

- interface/src/SpeechRecognizer.h
- libraries/controllers/src/controllers/ScriptingInterface.h
- libraries/controllers/src/controllers/impl/MappingBuilderProxy.h
- libraries/controllers/src/controllers/impl/RouteBuilderProxy.h
- libraries/networking/src/MessagesClient.h
Updates controller mapping names in API docs to use "com.vircadia..." instead of "com.highfidelity...".
> Update API examples to use "vircadia" in mapping names.

- interface/src/main.cpp
Just happened to notice this. I could be wrong, but I did compile and run the interface with no apparent issues.
> Remove <thread> library from main.cpp.

- assignment-client/src/Agent.cpp
- assignment-client/src/audio/AudioMixer.cpp
- assignment-client/src/scripts/EntityScriptServer.cpp
- interface/src/Application.cpp
- interface/src/ui/HMDToolsDialog.cpp
- libraries/audio-client/src/AudioClient.cpp
- libraries/plugins/src/plugins/InputConfiguration.cpp
- libraries/plugins/src/plugins/PluginManager.cpp
- libraries/plugins/src/plugins/PluginUtils.cpp
The returned plugin lists are all coming back as "const&" and in most cases are assigned to "auto" (which strips out qualifiers).
This adds in as many "const auto&" ref qualifiers as I could for plugin references so as to reduce unnecessary copies.
(This came out of a tooltip while poking at the networking code)
Testing focus:
* The only thing I can think of is "make sure all plugins are recognized and used". This code assumes that the list of plugins is set before the first call returns and never changes?
* If the list of plugins changes after launch somehow then this may cause crashes.
* Also maybe "check for shutdown crashes" in case the list of plugins is destroyed while it's still being used by someone?
> Housekeeping: Update use of "auto" with plugin lists.

- .github/workflows/pr_build.yml
This PR disables compiler optimization for the self hosted aarch64 runner.
Apparently the compiler optimization needs ~75 minutes extra, which slows everything down quite a bit.
This has no downside, since the builds aren't even getting uploaded yet.
> GHA: Disable compiler optimization on self-hosted runner.

- interface/resources/qml/hifi/audio/PlaySampleSound.qml
- interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
- interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
- interface/src/avatar/MyAvatar.h
I don't know how this code was working before or why the position was needed, but the comments suggest that removing the position argument was the initial intention and the output test seems to work fine for me without it. May or may not fix https://github.com/vircadia/vircadia/issues/1453.
> Remove second argument from some playSystemSound() calls in QML.

- .gitmodules
- CMakeLists.txt
This is no longer useful because the Web app no longer includes the Web SDK as a submodule. Instead, support optionally cloning the Web app and/or Web SDK into subdirectories and include their files if present in the IDE solution.
> Remove Vircadia Web app submodule and add automatic detection instead.

- scripts/communityScripts/explore/explore.html
Simple change that is using the placename instead of the "address" feild from the place api to build the url to connect.
For those where the placename = the domain name, Interface will be able to resolve path correctly.
using the address, this makes interface using 100% of the time the ip:/port information.
> Explore App: Use the placename instead of address (ip:port).

- scripts/system/create/entitySelectionTool/entitySelectionTool.js
Fix for Issue #1517
Locked entities were simply ignored and it was still processing their children.
Now it's no more possible to duplicate if the selection and their children contains a locked entities.
It was also unable to add the new parent if the duplicated child entity was locked. Which was causing some other issues.
> Create App: Prevent locked entities and their children from being duplicated.

- libraries/model-serializers/src/GLTFSerializer.cpp
Fixes https://github.com/vircadia/vircadia/issues/1542
> Update loops to prevent crash on some GLTF models.

- libraries/model-baker/src/model-baker/Baker.cpp
- libraries/model-baker/src/model-baker/CalculateBlendshapeNormalsTask.cpp
- libraries/model-baker/src/model-baker/CalculateBlendshapeTangentsTask.cpp
- libraries/model-baker/src/model-baker/CalculateMeshNormalsTask.cpp
- libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.cpp
- libraries/model-serializers/src/GLTFSerializer.cpp
This should make no functional difference, but get rid of ~20 warnings.
This is based on top of PR #1468
> Replace the deprecated QVector::fromStdVector and QVector::toStdVector().

- .github/workflows/pr_build.yml
- interface/src/Application.cpp
This removes a weird workaround from HiFi times.
Whatever the reason for this was, it basically breaks crashpad for deadlocks because no one is going to sit around and wait 10 minutes for Interface to detect a deadlock when it is not responsive.
Two minutes already seems like quite a stretch in most cases.
> Remove extended deadlock wait on macOS

- libraries/shaders/src/shaders/Shaders.cpp
Memcpy parameters were in wrong order, so loadSpirvResource returned uninitialized memory region.
I tested change on Linux, and it doesn't break anything.
> Fixed memcpy in loadSpirvResource

- hifi_qt.py
This PR adds Linux Mint 19.x to the Qt package selector to make building more comfortable on this operating system.
> Choose right Qt version for Linux Mint 19.x

- .github/workflows/pr_build.yml
As of present  just attempts to install  a previous version of NSIS. This will likely fail, but I want to see how GHA complains.
> Resolve #1557 where Windows builds fail on GHA due to incompatible NSIS version.

- .github/workflows/master_build.yml
Mirrors changes in #1560 to the `master_build.yml`.
> Mirror NSIS fix for PR builds to master builds on GHA.

- interface/src/ModelPackager.cpp
- libraries/model-serializers/src/FST.cpp
- libraries/model-serializers/src/FSTReader.cpp
- libraries/model-serializers/src/FSTReader.h
Fixes #1535
Tested with the model included in that issue, seems to work fine now.
> Fix MultiHash issues added in PR #1468.

- interface/src/Util.cpp
- interface/src/commerce/Wallet.cpp
- libraries/networking/src/AccountManager.cpp
- libraries/networking/src/DomainAccountManager.cpp
- libraries/networking/src/UserActivityLogger.cpp
- libraries/octree/src/OctreeDataUtils.cpp
Fixes some warnings. Shouldn't make any functional difference.
> Housekeeping: Explicitly encode QStrings to utf8.

- hifi_qt.py
I was getting a confusing "Sorry, Manjaro Linux on x86_64 is too old and won't be officially supported. Please upgrade to a more recent Linux distribution." error message from cmake instead of the usual suggestion to build Qt or use the system version. From the recent changes in hifi_qt.py it seems like this would happen on all Linux distros other than Ubuntu and Mint, so this PR fixes it to make no assumptions for distros that we don't have explicit version checks for, as before.
> Fixed some Linux distros being deemed unconditionally too old to use Qt.

- libraries/ui/src/OffscreenUi.cpp
- libraries/ui/src/OffscreenUi.h
- libraries/ui/src/VrMenu.cpp
- libraries/ui/src/VrMenu.h
This removes the usage of QObjectUserData, setUserData and userData.
The actual change is minor but this required rearranging things a bit. MenuUserData class is now declared in the header so that the Q_OBJECT macro is processed properly.
Fixes #1305
Builds on top of https://github.com/vircadia/vircadia/pull/1485
> Remove deprecated usage of setUserData.

- libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
Addresses: https://github.com/vircadia/vircadia/issues/794
`devicePixelRatio()` which returns an integer is unsuitable when the user's DPI is not a multiple of 100%. Changing this to `devicePixelRatioF()` allows the interface to work correctly on desktops where a fractional scale is used as it returns a float.
Tested on Linux KDE with a scale of 100% and 140% - both work fine
> Replace call to devicePixelRatio() with devicePixelRatioF().

- interface/src/Menu.cpp
- interface/src/Menu.h
- libraries/entities-renderer/src/EntityTreeRenderer.cpp
- libraries/entities-renderer/src/EntityTreeRenderer.h
- libraries/entities-renderer/src/RenderableModelEntityItem.cpp
- libraries/script-engine/src/SceneScriptingInterface.cpp
- libraries/script-engine/src/SceneScriptingInterface.h
Adds a Developer menu item: `Developer > Render > Green Boxes For Missing Models`
Also adds a property and a signal to the `Scene` scripting API. These API items are used by the Developer menu item.
> Add option to render green boxes for missing models.

- interface/resources/qml/LoginDialog/SignUpBody.qml
- interface/src/ui/LoginDialog.cpp
- interface/src/ui/LoginDialog.h
If email confirmation is required a popup is shown instead of
attempting to login immediately,
Various Metaverse server API error cases handled and reported/logged.
Supersedes https://github.com/vircadia/vircadia/pull/1566
> Improve Metaverse sign-up UX.

- cmake/ports/sdl2/fix-build-against-wayland-1_20.patch
- cmake/ports/sdl2/portfile.cmake
I was getting linking errors from hifiSDL2 plugin on Manjaro similar to what is described [here](https://www.linuxquestions.org/questions/slackware-14/regression-on-current-with-sdl2-4175704819-print/), so applied a patch in the same vein as well.
Wayland version: 1.20.0-1
<details>
<summary>The actual errors</summary>
```
[ 82%] Linking CXX shared library libhifiSdl2.so
/usr/sbin/ld: /home/namark/vircadia-files/vcpkg/2f668515/installed/x64-linux/lib/libSDL2.a(SDL_waylandvideo.c.o): in function `wl_display_get_registry':
/home/namark/vircadia-files/vcpkg/2f668515/buildtrees/sdl2/x64-linux-rel/wayland-generated-protocols/wayland-client-protocol.h:1032: undefined reference to `wl_proxy_get_version'
/usr/sbin/ld: /home/namark/vircadia-files/vcpkg/2f668515/buildtrees/sdl2/x64-linux-rel/wayland …
```
> Fix sdl2 linking errors when built against new Wayland.

- hifi_qt.py
This error was reported on discord
```
-- EXTERNAL_BUILD_ASSETS: https://athena-public.s3.amazonaws.com
-- GLES_OPTION:
Using the Python interpreter located at: /usr/bin/python3.10
-- The CXX compiler identification is GNU 11.1.0
GCC compiler detected, adding -O3 -fPIC -ggdb flags
-- VIRCADIA_OPTIMIZE: true
Adding CPU architecture flags: -march=native -mtune=native
-- VIRCADIA_CPU_ARCHITECTURE: -march=native -mtune=native
-O3 -fPIC -ggdb -march=native -mtune=native
['/home/ben/build/vircadia/prebuild.py', '--release-type', 'DEV', '--build-root', '/home/ben/build/vircadia/build']
Using a packaged Qt
Traceback (most recent call last):
File "/home/ben/build/vircadia/prebuild.py", line 194, in <module>
main()
File "/home/ben/build/vircadia/prebuild.py", line 119, in main
qt = …
```
> Safer linux distro version checks in Qt installation script.

- hifi_utils.py
There is a newer, higher level officially recommended python [requests library](https://docs.python-requests.org/en/latest/) that can take care of all this mess, but I'm not sure if it's ok to introduce it here as a dependency.
> Fix dedicated IPFS gateway rejecting download requests.

- interface/resources/qml/LoginDialog/LinkAccountBody.qml
I tried hosting my own private metaverse server so I wouldn't have to make a centralized account, and it worked great... there's just one problem:
The official client can't connect to it!
This fixes that, sort of. It lets you set HIFI_METAVERSE_SERVER (like the domain server already has) and also HIFI_AUTHABLE_HOSTNAMES (a comma-separated list) to set which domains get your credentials passed to them.
> UI for setting metaverse server on login

- interface/src/scripting/WindowScriptingInterface.h
[Documentation](https://apidocs.vircadia.dev/Window.html#.prompt) for ```Window.prompt()``` states that if the user click "Cancel" it will return ```""```
It does, in fact return ```null```, I don't know if that is intentional but arguments could be made for both.
This just updates the documentation and the example .
> Update API documentation for Window.prompt().

- BUILD_LINUX.md
Adds an Arch Linux build guide below the existing Ubuntu guide.
Following these steps on a VPS, I was able to successfully run the server and access it via browser.
I was unable to test the interface due to it being a VPS without a GPU and window manager.
> Add Arch Linux build guide.

- .github/workflows/master_build.yml
- .github/workflows/pr_build.yml
to see if it fixed a specific build issue on windows.
> Enabled vcpkg bootstrapping in PR and master builds.

- hifi_singleton.py
- prebuild.py
The build was getting stuck for me with the following output
```
$ cmake ..                                                                                                                    
-- GLES_OPTION:                                                                                                                                                                       
Using the Python interpreter located at: /usr/bin/python3.8                                                                                                                           
-- The CXX compiler identification is GNU 9.3.0                                            
GCC compiler detected, adding -O3 -fPIC -ggdb flags                                        
-- VIRCADIA_OPTIMIZE: true …
```
> Fixed python prebuild script getting stuck trying to lock a file without permission.

- .github/workflows/master_build.yml
- .github/workflows/pr_build.yml
as Visual Studio 2022 couldn't build nvidia texture tools with an
internal compiler error. This is likely a bug on their side and hopefully will be fixed in future releases.
> Downgraded GHA Windows environment to Server 2019.

- .github/workflows/master_build.yml
- .github/workflows/pr_build.yml
This PR reverts https://github.com/vircadia/vircadia/pull/1606 as it's no longer necessary after https://github.com/vircadia/vircadia/pull/1616, and it breaks the aarch64 build. 
This is an alternative for https://github.com/vircadia/vircadia/pull/1632 and https://github.com/vircadia/vircadia/pull/1608.
> Disable VCPKG bootstrapping in automated builds.

- libraries/networking/src/udt/NetworkSocket.cpp
- libraries/networking/src/udt/NetworkSocket.h
- libraries/networking/src/udt/Socket.cpp
- libraries/networking/src/udt/Socket.h
- libraries/vircadia-client/src/internal/Context.cpp
Based on #1630
Apparently the settings thread was lingering and preventing proper cleanup, which caused a lot of problems like not being able to run all unit tests in the same process or run Unity SDK code in Unity Editor more than once. This might be indicative of some other problem, but for now just disabling it seems to work fine.
> Fixed client library context destruction. 

- hifi_vcpkg.py
This function changed when IPFS support was added to the build system, but the android code path was overlooked since the build was failing anyway. Stumbled upon this when hacking together an android build for native client library. Now the android build will still fail, but with a different error.
> Fixed download function call for android dependencies.

- libraries/shared/src/shared/FileLogger.cpp
Shared library was refactored (split in two parts) to not depend on QtGui. Since this header is unused it doesn't result in a runtime dependency, but it is preventing building native client library using custom Qt build without GUI headers/module.
> Removed unnecessary QtGui include in shared library.

- INSTALLER.md
Fix the issue of "Plugin not found, cannot call xxxx::xxx " when using x86-unicode. (e.g. Plugin not found, cannot call nsProcess::_FindProcess)
> Update INSTALLER notes for Windows.

- hifi_utils.py
Network and checksum errors are output only if all fallbacks fail.
> Improve package download error logging in python build scripts.

- libraries/entities/src/ZoneEntityItem.h
No change in function: the old and new init values are the same (0).
> Fix Zone entity avatar priority default initialization.

- .github/workflows/pr_build.yml
I am shutting down the self-hosted aarch64 GitHub Actions Runner, so this PR removes it from the pipeline and removes code that is specific to the Runner.
I will keep the Runner online for a couple of days more, to not cause checks to suddently fail and people wondering why their builds are failing.
> Remove self-hosted GitHub Actions Runner and Runner dependent code.

- interface/src/avatar/OtherAvatar.cpp
- libraries/animation/src/Rig.cpp
- libraries/animation/src/Rig.h
- libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
- libraries/avatars-renderer/src/avatars-renderer/Avatar.h
- libraries/avatars/src/AvatarData.cpp
- libraries/avatars/src/AvatarData.h
In particular, for a particular avatar, the Web client sends a skeleton and joint with different joint order to that which the native client loads to render the Web client avatar. Thus, the order of the joints data received needs to be mapped onto the native client avatar model / rig.
Known issue: When a Web avatar is first rendered in the native client, it can be rendered distorted for up to a few seconds. The cause of this issue is unknown and a work-around has not been found to date.
> Handle skeleton joints from other clients having different order.

- assignment-client/src/entities/EntityServer.cpp
- domain-server/resources/describe-settings.json
- domain-server/src/DomainServer.cpp
- libraries/entities-renderer/src/RenderableWebEntityItem.cpp
- libraries/material-networking/src/material-networking/TextureCache.cpp
- libraries/networking/src/AssetUtils.cpp
- libraries/networking/src/DomainHandler.h
- libraries/networking/src/FileResourceRequest.cpp
- libraries/networking/src/MetaverseAPI.cpp
- libraries/networking/src/MetaverseAPI.h
- libraries/procedural/src/procedural/Procedural.cpp
- libraries/qml/src/qml/OffscreenSurface.cpp
Not perfect in terms of communicating the setting to assignment clients https://github.com/vircadia/vircadia/issues/1727, but should be good at least for use cases that don't rely on that. Also the ICE server needs to be separately configured with the same Metaverse URL to authenticate domain servers https://github.com/vircadia/vircadia/issues/1729.
> Added metaverse server URL setting in domain server admin panel.

- .github/workflows/master_build.yml
- .github/workflows/pr_build.yml
The GHA runner was running out of disk space, and also at some point upgraded the C++ standard library to a version that is not available in plain Ubuntu 20.04. Workarounds taken from https://github.com/jens-maus/RaspberryMatic/blob/d5044bef3307bc61166377c162569de1a61cf332/.github/workflows/ci.yml#L34-L40 and https://github.com/actions/runner-images/issues/3432. If Github fixes these issues in the future the workaround might fail and would need to be removed, but reading through some similar issues I've found I'm not sure what their stance on this is.
> GHA ubuntu 20.04 build fixes.

- .github/workflows/master_build.yml
- .github/workflows/pr_build.yml
https://github.com/orgs/community/discussions/47863
> Workaround for GHA Ubuntu 20.04 grub-efi-amd64-signed package issue.
