vircadia/vircadia-native-core

libraries/script-engine/src/ScriptEngine.cpp
Fixes bug where "" (empty) causes all scripts to be whitelisted. Also improved debug log clarity with a prefix.
=> Fixes Entity Script Whitelist

interface/resources/qml/hifi/dialogs/security/EntityScriptWhitelist.qml
Adds a proof of success or failure when saving changes on the QML, editing the text area will cause the message to disappear as to avoid confusion. Instructions explaining the whitelist have been added to the QML as well.
=> Added a confirmation message + instructions to the QML.

scripts/community/chat.js, scripts/defaultScripts.js
This adds a community directory under the scripts directory. George Deacon's chat app has been placed within, and is loaded as a default script.
=> Adds community script directory, adds chat as default app.

cmake/ports/sdl2/CONTROL
vcpkg doesn't like unexpected blank lines. Live and learn.
=> Fix the fix for SDL2

CMakeLists.txt
Having a "hifi.sln" file feels wrong. Let's fix that.
=> Update Primary CMakeLists project name to Athena

BUILD.md, BUILD_ANDROID.md, BUILD_LINUX.md, BUILD_WIN.md
Just a small update to build instructions to account for new branding and repository name shift
=> Update a small portion of the build instructions

interface/src/Application.cpp
Change window title from "High Fidelity" to "Project Athena"
=> Update interface window title

interface/resources/images/project-athena-banner-color2.svg, interface/resources/qml/LoginDialog.qml, interface/resources/qml/LoginDialog/LinkAccountBody.qml, interface/resources/qml/LoginDialog/SignUpBody.qml, interface/resources/qml/LoginDialog/UsernameCollisionBody.qml, interface/src/workload/PhysicsBoundary.cpp
Rebranded QML dialogs for account creation/login/TOS etc. and created a temporarary banner svg.
=> Rebranding of login dialogs etc. QML

scripts/communityModules/chat/FloofChat.js, scripts/communityModules/chat/FloofChat.qml
This already works and stuff, this is just a last minute push/merge to allow for goto json support!
if you want to test,
(all are via the chatbar)
"/goto the" should take you to thepalace via its IP
"/gotos the" should take you there without confirmation
"/goto longcat" should take you to longcat via its placename
pressing up/down on the chatbar should give you history
:3
=> Add goto json support (defaults to darlings goto), etc

scripts/communityModules/chat/FloofChat.html, scripts/communityModules/chat/FloofChat.js
Fixed not using json settings value.
Fixed url parsing in chat history (my bad), it may still be broken in the chat that shows up on screen.
But that's not clickable anyway!
to test just put urls in chat
=> Fixed url parsing breaking with text formatting! <3

interface/resources/qml/hifi/avatarapp/MessageBoxes.qml, interface/resources/qml/hifi/commerce/checkout/Checkout.qml, interface/resources/qml/hifi/commerce/purchases/Purchases.qml, interface/resources/qml/hifi/commerce/wallet/Help.qml, interface/src/Application.cpp, interface/src/avatar/MyAvatar.h, libraries/avatars-renderer/src/avatars-renderer/Avatar.h, libraries/avatars/src/AvatarData.h, libraries/image/src/image/TextureProcessing.h, libraries/midi/src/Midi.h, libraries/script-engine/src/ScriptEngine.h, libraries/script-engine/src/Vec3.h
Links updated in JSDoc and QML.
Issue: https://github.com/kasenvr/project-athena/issues/61
=> Replace links to docs.highfidelity.com

tools/jsdoc/hifi-jsdoc-template/static/styles/responsive.css, tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
The sidebar can now be toggled + the viewport restriction has been removed.
Preview these changes here: https://apidocs.projectathena.dev/staging/out/
Fixes: https://github.com/kasenvr/project-athena/issues/138
=> API Docs viewport restriction removal + menu toggle

interface/resources/qml/hifi/avatarapp/AvatarsModel.qml
To use place a jpg next to avatar fst with same name as fst.  jpeg should show up as thumbnail inside avatarapp when fst is worn.  Such as if your avatar fst is "bob.fst" the thumbnail next to it would be "bob.jpg".
=> feature: Allow users to set avatar thumbnails that show in avatar app.

launchers/pantheon/public/css/styles.css, launchers/pantheon/src/App.vue, launchers/pantheon/src/background.js, launchers/pantheon/src/components/Dialogs/CancelDownload.vue, launchers/pantheon/src/components/Dialogs/DownloadFailed.vue, launchers/pantheon/vue.config.js
- Change "download" button color immediate it is clicked.
- Provide a "cancel download" option when click the "download" during a download.
- Fix installer launching at start of second and subsequent downloads in addition to download end.
- Miscellaneous other fixes.
=> Pantheon launcher improvements

scripts/communityModules/chat/FloofChat.js
Created a chat relay on the metaverse server, grid chat now works again.
=> Fix chat server relay

interface/CMakeLists.txt
=> Change to Project Athena in Task Manager

libraries/entities/src/EntityScriptingInterface.h
=> Add link to top of Entities API docs for the list of entity types.

LICENSE
Testing: Check that the updated license is displayed in the installer.
Issue: https://github.com/kasenvr/project-athena/issues/216
=> Update license notice

scripts/communityModules/chat/FloofChat.js
=> Added license

libraries/networking/src/udt/PacketHeaders.h
It is as the comment says in the code. I've tested this on my local machine with a local domain-server and confirmed it to be working.
=> Bump packet version size up.

libraries/shared/src/shared/FileLogger.cpp
Just changed the log file name to from "hifi-.." to "vircadia-..".
Already build an tried it on linux, so it should be fine as it is such a small change.
=> Change log file name to "vircadia-.."

.github/workflows/master_build.yml
This PR should deal with the signing related errors which are happening on the test GHA builds for master merges
=> [gha-master-merge] bypass signing for now

scripts/system/create/edit.js
This change makes the Zones Selector sorted by zone names.
To address issue: renderWithZones: zone list incorrectly sorted. #354
(But this doesn't fix the problem with the scrolling)
=> Zones Selector sorted by zone names

scripts/system/create/edit.js
This problem was introduced with this commit https://github.com/kasenvr/project-athena/commit/2fc0f01928bf94bf1bd3dfafbd7b1b84c4d68ae9#diff-48b43e48f4b869756959f7bd81c1887a 
Closes #380
=> Bugfix: Create app now uses proper dimensions on create

libraries/fbx/src/GLTFSerializer.cpp
https://github.com/kasenvr/project-athena/issues/415
=> Fix issues with glb urls

libraries/entities-renderer/src/EntityTreeRenderer.cpp
Fixes https://github.com/kasenvr/project-athena/issues/407
=> Bugfix: Add null check to entity render clearing to fix crash.

scripts/system/inspect.js
This allows you to inspect entities more closely using the Alt-click camera controls.
For @Aitolda .
=> Reduce minimum inspect distance

interface/resources/qml/OverlayLoginDialog.qml
=> Update login overlay to Vircadia.

scripts/communityScripts/explore/explore.html, scripts/communityScripts/explore/explore.js, scripts/defaultScripts.js
To be merged after https://github.com/kasenvr/Decentralized_GoTo_Experimental/pull/4 is merged and its changes are added to this PR.
=> Remove old goto, update Explore app.

libraries/controllers/src/controllers/UserInputMapper.cpp, libraries/controllers/src/controllers/UserInputMapper.h
https://sentry.vircadia.dev/organizations/vircadia/issues/25/
Test plan:
- In the console, type `Controller.getAvailableInputs(9999999)`.  In master you would crash.  Now you don't crash.
- In the console, type `Controller.getActionValue(9999999)`.  In master you would crash.  Now you don't crash.
=> Fix various crashes/issues in controller scripting API

libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp, libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
Fixes the underlying bug behind https://github.com/kasenvr/project-athena/issues/479 (but doesn't add the requested feature)
=> Properly pause particles when you look away

assignment-client/src/entities/EntityServer.cpp, libraries/entities/src/EntityTree.cpp, libraries/entities/src/EntityTree.h
https://github.com/kasenvr/project-athena/issues/434
needs testing on server and client
=> Possible fix for entity server crash

hifi_android.py
This is for fixing Android builds. It needs testing.
Also the URL will probably change to a vircadia.com one (waiting on Kalila for that)
=> Change Android URLs to Linode bucket, old HiFi one is gone

interface/src/Application.cpp, libraries/entities/src/EntityTree.cpp, libraries/entities/src/EntityTree.h, libraries/octree/src/Octree.cpp, libraries/octree/src/Octree.h
=> Import entities now works on domains that you do not have rights on.

interface/resources/qml/ConnectionFailureDialog.qml, interface/resources/qml/dialogs/TabletConnectionFailureDialog.qml
=> Update the connection failure dialog 'go to' -> 'explore'

libraries/entities-renderer/src/RenderableModelEntityItem.cpp, libraries/render-utils/src/Model.cpp, libraries/render-utils/src/Model.h
https://github.com/kasenvr/project-athena/issues/559
=> Make sure renderWithZones works on models on restart/reload

libraries/entities-renderer/src/RenderableShapeEntityItem.h
https://github.com/kasenvr/project-athena/issues/491
=> Fix shape alpha 0 issue

interface/src/avatar/MyCharacterController.cpp, interface/src/avatar/OtherAvatar.cpp, libraries/physics/src/CharacterController.cpp
This fixes https://github.com/kasenvr/project-athena/issues/48, not https://github.com/kasenvr/project-athena/issues/77
=> Fix lag on restart with scaled avatar

libraries/entities/src/EntityTree.cpp
fixes https://github.com/kasenvr/project-athena/issues/562
=> renderWithZones works on import from JSON

libraries/octree/src/Octree.cpp, libraries/octree/src/OctreeEntitiesFileParser.cpp, libraries/octree/src/OctreeEntitiesFileParser.h
Per CR of https://github.com/kasenvr/project-athena/pull/586 .
=> Tidy JSON relative URLs importing code

interface/resources/qml/hifi/avatarapp/AvatarsModel.qml
An attempt to resolve avatar app slowdown some users are experiencing, going to first rule out xmlrequest.
=> Test moving to qt image error handling in avatar app

BUILD_OSX.md
(p.s. I didn't actually check to see if this works, but I assume it did!)
=> Update OSX folder icons to Vircadia & OSX build docs

interface/resources/qml/hifi/AssetServer.qml, interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
Testing:
- Test in both desktop and HMD.
- Test both .gltf and .glb files.
=> Fix GLB files not being able to be added from Asset Server

scripts/communityScripts/chat/FloofChat.html, scripts/communityScripts/notificationCore/notificationCore.js
The chat window triggering is pretty much working now, you can check that by typing a message while in world with another person and clicking on the message popup at the bottom left of the screen. When the chat window opens for you, it should not open for anyone else in the domain.
Alongside those changes, I've also refactored links for: images, videos, and regular links. Please try all three link types, right click and ensure copying them works appropriately. Also try clicking on them directly to ensure there's no regression of functionality there.
=> Fix chat opening due to other users triggering

libraries/entities/src/EntityScriptingInterface.h
Related to helping address https://github.com/kasenvr/project-athena/issues/786 by mentioning the issue.
=> Update API docs to specify entity-server-script findEntities caveat.

scripts/defaultScripts.js, scripts/system/onFirstRun.js
This script will have things to run on first run, the first of which is a prompt to ask the user to set a display name.
=> First run script.

interface/src/ui/Stats.h
=> Update decimatedTextureCount apidoc

domain-server/resources/web/settings/js/settings.js
It does what it says! Try to use that dialog successfully... try to break it by inputting illegal characters "%$#%#$%!@#", see if it breaks for you. Otherwise, should be good to go. :)
=> Fix domain-server settings "Create new domain ID" dialog.

assignment-client/src/scripts/EntityScriptServer.cpp, libraries/entities-renderer/src/EntityTreeRenderer.cpp, libraries/entities-renderer/src/EntityTreeRenderer.h, libraries/entities/src/EntityScriptingInterface.cpp, libraries/entities/src/EntityScriptingInterface.h
Reverts kasenvr/project-athena#659
Due to high amounts of world load failures.
=> Revert "Split Local and owned Avatar Entity scripts into their own ScriptEngine"

.github/workflows/pr_build.yml
Code from commit 4c536f4 by HifiExperiments.
=> Replace set-env in PR GHA

assignment-client/src/scripts/EntityScriptServer.cpp, libraries/entities-renderer/src/EntityTreeRenderer.cpp, libraries/entities-renderer/src/EntityTreeRenderer.h, libraries/entities/src/EntityScriptingInterface.cpp, libraries/entities/src/EntityScriptingInterface.h, libraries/script-engine/src/ScriptEngine.cpp, libraries/script-engine/src/ScriptEngine.h, libraries/script-engine/src/ScriptEngines.cpp
=> Revert "Revert "Split Local and owned Avatar Entity scripts into their own ScriptEngine""

interface/src/scripting/PlatformInfoScriptingInterface.cpp
=> Fix small typo in getPlatformTierNames()

BUILD.md, BUILD_WIN.md, INSTALLER.md
See files changed for details!
* Added NodeJS requirements to build Athena codebase.
* Various formatting fixes.
=> Update build docs slightly.

domain-server/resources/web/js/shared.js, domain-server/resources/web/wizard/js/wizard.js
Closes #1001
Closes #1002 
Closes #1003 
To test, run through the wizard and ensure that all three of these issues above are no longer an issue.
=> Various Domain Server Wizard Fixes

libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp, libraries/render-utils/src/Model.cpp
fixes https://github.com/vircadia/vircadia/issues/1027
=> Fix for offset soft attachments

BUILD_ANDROID.md
Updated instructions for building Oculus Quest with latest Android Studio, including additional troubleshooting tips.
=> Updated build instructions for Oculus Quest

BUILD.md, BUILD_OSX.md, hifi_qt.py, screenshare/package-lock.json, tools/qt-builder/README.md
Reverted two changes from last PR
=> MacOS Qt 5.15.2

cmake/macros/GenerateInstallers.cmake
Add release name to end of installers.
=> Add release name to end of installers.

interface/src/Application.cpp, libraries/script-engine/src/ScriptEngine.cpp
Original testing of this fix was done on the following PRs:
- https://github.com/vircadia/vircadia/pull/1023 (master)
- https://github.com/vircadia/vircadia/pull/1024 (master)
- https://github.com/vircadia/vircadia/pull/1031 (Qt 5.15.2 branch)
- https://github.com/vircadia/vircadia/pull/1032 (Qt 5.15.2 branch)
=> Fix OSX crash on shutdown

BUILD.md, BUILD_ANDROID.md, BUILD_OSX.md
This PR defines the language of some codeblocks in the build documentation to work correctly in our documentation system.
=> Define code block language to fix sphinx warnings

libraries/networking/src/FingerprintUtils.cpp
We do this by using either /etc/machine-id, or hashing the MACs of all
non-virtual networking devices.
We make this fingerpint unique to our platform by adding our own string
to the hash, and add some stretching for good measure. This way Vircadia's
fingerprint isn't going to match the system's ID or anything another
application generates.
=> Implement Linux machine fingerprints

.github/stale.yml
This bot will help triage issues (or so I think) in accordance with the configuration file defined here.
=> Activate stale bot

scripts/system/create/modules/brokenURLReport.html
This file is incredibly annoying on Linux, where it's tagged as automatically modified due to line ending conversion.
This should fix that.
=> Convert line endings from CRLF to LF

libraries/gpu/src/gpu/Texture_ktx.cpp
fix https://github.com/vircadia/vircadia/issues/1137
Note: if you've already experienced the issue, you'll have to clear your ktx cache for things to get back to normal, I think.  but make sure to test by copying over a ktx_cache from the current release
=> Fix ktx issue

libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
=> Remove unused variable

interface/resources/qml/hifi/Pal.qml
Fix Pal ban buttons overlapping with width (maybe...) and add descriptions for new ban button.
=> Update Pal.qml for new Ban button

BUILD_WIN.md
Adds Qt build information (env vars, required packages) to BUILD_WIN.md, and fixes a few existing typos.
=> Update BUILD_WIN.md with Qt Info

libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp
Missed in PR1212. I've done a file system search and this is the only one missed.
=> Fix missed JSDoc tag change

tools/jsdoc/config.json, tools/jsdoc/hifi-jsdoc-template/publish.js, tools/jsdoc/hifi-jsdoc-template/static/CNAME, tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl, tools/jsdoc/package.json, tools/jsdoc/root.js
I've fixed some metadata and also added a static file "CNAME" which resides in the api-docs repo but not here.
=> Some APIDocs metadata fixes.

INSTALLER.md
These will be revised at a later date with corrections and/or specifics as I run through the process more times.
=> Add basic MSIX instructions to INSTALLER.md.

domain-server/resources/web/wizard/index.shtml, interface/resources/html/tabletHelp.html, interface/resources/qml/hifi/avatarPackager/AvatarPackagerApp.qml, interface/resources/qml/hifi/avatarPackager/AvatarProject.qml, interface/resources/qml/hifi/avatarapp/MessageBoxes.qml, interface/resources/qml/hifi/commerce/checkout/Checkout.qml, interface/resources/qml/hifi/commerce/purchases/Purchases.qml, interface/resources/qml/hifi/commerce/wallet/Help.qml, interface/src/Application.cpp, interface/src/avatar/AvatarDoctor.cpp, interface/src/avatar/MyAvatar.h, libraries/avatars-renderer/src/avatars-renderer/Avatar.h, libraries/avatars-renderer/src/avatars-renderer/ScriptAvatar.h, libraries/avatars/src/AvatarData.h, libraries/avatars/src/ScriptAvatarData.h, libraries/image/src/image/TextureProcessing.h, libraries/midi/src/Midi.h, libraries/script-engine/src/ScriptEngine.h, server-console/src/content-update.html, server-console/src/splash.html, tools/jsdoc/api-mainpage.md
I don't think this would need much in the way of testing in the native Interface itself, however any and all testing is welcome!
=> Update user docs links "docs.vircadia.dev" -> "docs.vircadia.com".

domain-server/src/NodeConnectionData.cpp, libraries/networking/src/DomainHandler.h, libraries/networking/src/LimitedNodeList.h, libraries/networking/src/webrtc/WebRTCDataChannels.cpp
Builds on top of PR https://github.com/vircadia/vircadia/pull/1296.
Works in conjunction with Web SDK PR https://github.com/vircadia/vircadia-web-sdk/pull/23.
Merge sequence:
See Web SDK PR https://github.com/vircadia/vircadia-web-sdk/pull/23.
=> Anonymous Web SDK connection to domain server

libraries/networking/src/webrtc/WebRTCDataChannels.h
This PR builds on top of PR https://github.com/vircadia/vircadia/pull/1296.
Merge sequence:
=> Fix a couple of WebRTC Doxygen typos

interface/src/Application.cpp
Also emit the full path to the file in the exception.
This should help with figuring out #1308
=> Log the location of the primary resources file

libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
Fixes int32 overflow in automatic texture memory procedure
=> Fix automatic texture memory bug.

interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
This is a work in progress, but potentially useful.
=> Separate rendering effect settings.

scripts/system/create/entityProperties/html/js/entityProperties.js, scripts/system/create/modules/brokenURLReport.js, scripts/system/html/css/edit-style.css
This PR adds a "**Add All Zones**" button to the Multiple Zones Selector component (used for "renderWithZones")
**This addresses issue #775**
That PR also contains a small bug fix for the "**Broken Url Report**" for the error 0.
Previously it was referring to "_Url not well formed_" (which wasn't exact for all the possible causes)
Now it will displays "_Server not found_".
=> Create App - "Add All Zones" on renderWithZones selector.

.github/workflows/master_build.yml, .github/workflows/pr_build.yml
This PR adds a checksum check for the macOS SDK.
Not sure why I had problems with this before, but it works now.
=> GHA: Add checksum for macOS SDK for PR and master builds.

tools/qt-builder/README.md
This PR updates the tools/qt-builder/README.md with some additional info on how to get Qt to build, work around bugs, and some elaboration.
=> Update qt-builder readme for macOS

libraries/model-serializers/src/GLTFSerializer.cpp
Fixes incorrect handling of "metallicFactor" value on GLTF import.
=> Fixed metallic material import for glTF.

BUILD_LINUX.md, BUILD_OSX.md, README.md
The Linux documentation was quite gnarly, so hopefully I untangled it a bit (though not entirely). I did not check to see if information was out of date.
=> Documentation format revisions.

BUILD_LINUX.md
I added the change directory to repository folder command after cloning the git repo for the Arch build guide.
=> Updated Arch Linux Build Doc to Recorder Directory Command.

libraries/networking/src/NodeType.h, libraries/networking/src/udt/NetworkSocket.cpp, libraries/networking/src/udt/NetworkSocket.h, libraries/networking/src/udt/Socket.cpp, libraries/networking/src/udt/Socket.h, libraries/vircadia-client/src/internal/Context.cpp, libraries/vircadia-client/src/node_list.cpp, libraries/vircadia-client/src/node_list.h, libraries/vircadia-client/src/node_types.cpp, libraries/vircadia-client/src/node_types.h, libraries/vircadia-client/tests/client.cpp, libraries/vircadia-client/tests/common.h, libraries/vircadia-client/tests/messages.cpp
Also includes some fixes in the unit tests. 
Based on #1638
=> Client library APIs for accessing node type and active state.

.github/workflows/pr_build.yml
Builds should be available under Checks -> Artifacts
=> Use GHA build artifacts instead of custom uploader.

scripts/communityScripts/explore/explore.html
Filtering is now done in the server. Server's pagination is worked around by requesting maximal entry count per page, but will need to be handled properly in the future.
=> Fixed Metaverse places request in explore app.

LICENSE
Signed-off-by: 10allday <10allday@protonmail.com>
=> Update `Vircadia contributors` copyright to 2022.

LICENSE, domain-server/src/DomainServer.cpp, domain-server/src/DomainServerExporter.h
Including information on WebRTC configuration, exporters and audio codec preference.
=> Added capabilities object to domain server -> metaverse heartbeat requests.

domain-server/resources/describe-settings.json, domain-server/src/DomainServer.cpp, libraries/networking/src/LimitedNodeList.cpp, libraries/networking/src/LimitedNodeList.h, libraries/networking/src/NodeList.cpp, libraries/networking/src/NodeList.h, libraries/networking/src/udt/NetworkSocket.cpp, libraries/networking/src/udt/NetworkSocket.h, libraries/networking/src/udt/Socket.cpp, libraries/networking/src/udt/Socket.h, libraries/networking/src/webrtc/WebRTCDataChannels.cpp, libraries/networking/src/webrtc/WebRTCDataChannels.h, libraries/networking/src/webrtc/WebRTCSocket.cpp, libraries/networking/src/webrtc/WebRTCSocket.h
=> Settings for WebRTC signaling server port and ICE server list.
